### ISSUE TITLE
能把popup页面封装成一个chrome app吗？谢谢您

### ISSUE THREAD

**Issue by heartacker** [Selection-Translator/crx-selection-translate#119]
这样。弹出的小窗口我就 可以翻译了，太感谢
![qq 20160213235123](https://cloud.githubusercontent.com/assets/1876302/13028547/2111cbd6-d2ad-11e5-8f56-0518c390b774.png)

**Comment by lmk123** [comment]
我很好奇你这是什么浏览器，为嘛 Popup 页还可以分离出来的。。

**Comment by zhangnew** [comment]
Chrome 上这个 Popup 页弹出很慢，点击图标过1-2s才出来，以前很快的，感觉不到延迟
