### ISSUE TITLE
翻译目的语言设置无法保存？

### ISSUE THREAD

**Issue by jincola** [Selection-Translator/crx-selection-translate#125]
想把翻译目的语言固定改成英文，发现选项里面没有这项设置了（老版本我记得是有的），现在只能在弹出小窗口的右上角点击箭头，然后把“自动选择”改成英语。但是打开另一个网页，翻译目的语言就又成了中文。希望选项里面能加回这项设置，因为每次都要手动选择真的比较不方便。

**Comment by lmk123** [comment]
好，我会添加回来的。

**Comment by bytetour** [comment]
你好 最新的6.01版 好像又无法保存 目标翻译语言了。

**Comment by lmk123** [comment]
#291
