### ISSUE TITLE
何时能够添加单词本的功能呢？

### ISSUE THREAD

**Issue by yiluxin** [Selection-Translator/crx-selection-translate#129]
何时能够添加单词本的功能呢？

**Comment by lmk123** [comment]
本来我是不打算添加单词本功能的（[原因](https://github.com/lmk123/crx-selection-translate/issues/41#issuecomment-169955713)），但近期我在考虑要不要实现一个“收藏”功能。仅仅是收藏，不会有跟背单词相关的任何功能。

**Comment by yiluxin** [comment]
原来是这样。。感觉搜藏其实就是单词本

**Comment by lmk123** [comment]
我会添加这个功能的

**Comment by xifengxx** [comment]
期待中……

**Comment by lmk123** [comment]
#242
