### ISSUE TITLE
域名禁用添加白名单模式

### ISSUE THREAD

**Issue by ziyouwuji** [Selection-Translator/crx-selection-translate#139]
1、当在所有网站中禁用划词翻译功能后，无法控制当前网页禁用/启用；具体现象是所有网页禁用后，设置当前页面启用失败，不知道是否正常？
目前是想需要默认状态为关闭，然后通过控制当前网页禁用/启用开关实现有需要时使用插件功能。

2、弹窗打开时速度较慢，建议优化下。

3、在翻译时建议添加取消按钮，有遇到等待翻译一直显示在页面中无法消失。

**Comment by lmk123** [comment]
划词翻译的禁用/启用使用的是黑名单模式：默认全局启用，仅在某些网站中禁用；

但你想要的是白名单模式：默认全局关闭，仅在某些网站中启用。

你是这个意思吗？

**Comment by ziyouwuji** [comment]
嗯嗯，应该是说翻译盒子中对当前网页禁用/启用的优先级大于所有网站中禁用划词翻译这个模式；

目前是所有网站中禁用划词翻译功能后，在浏览器地址栏右边的图标按钮打开的翻译盒子中页面禁用/启用按钮无效；

**Comment by lmk123** [comment]
我明白你的意思了。

当你启用“在所有网站中禁用划词翻译”之后，再在翻译盒子中对某个网址启用时是无效的。

我会想想办法改进一下的。

**Comment by ziyouwuji** [comment]
嗯嗯，是这个意思，谢谢哈

**Comment by lmk123** [comment]
后续同步至 #259
