### ISSUE TITLE
popup 页面弹出太慢，老是等待google-analyze的响应。

### ISSUE THREAD

**Issue by heartacker** [Selection-Translator/crx-selection-translate#169]
实在是太慢了，每次popup 都很忙。。最后才发现，其实是一直等待google analyze，，等好了才加载出来。
![653e tm](https://cloud.githubusercontent.com/assets/1876302/15103657/824c8c30-15e0-11e6-97e5-772c59237b58.jpg)

**Comment by lmk123** [comment]
很奇怪的就是，我这边打开一直都很快，但你可能提供了一个重要的信息。我会深入调查一下

**Comment by Veeson** [comment]
@lmk123 每次点击图标弹出翻译框的时候确实有点慢，一般要一两秒以上，作者可以考虑优化一下。

**Comment by lmk123** [comment]
你用的是什么浏览器？

谷歌分析脚本是异步加载的（[源码](https://github.com/lmk123/crx-selection-translate/blob/master/src/public/ga.js#L22)），异步脚本是不会阻塞页面加载的——除非你的浏览器还不支持异步脚本：http://caniuse.com/#feat=script-async
