### ISSUE TITLE
建议根据字母的驼峰写法自动分词进行翻译.

### ISSUE THREAD

**Issue by zsedcbm** [Selection-Translator/crx-selection-translate#181]
在阅读各位程序员分享的源码中,很多涉及到 RecyclerView.ItemDecoration 类似这样的方法词的时候,分开翻译单词的话,比较容易理解,而不是现在这样直接当成一个单词,然后无法翻译.

**Comment by mcxinyu** [comment]
支持这个，程序猿必备。

**Comment by GavinAndre** [comment]
强烈支持 这个功能非常需要

**Comment by Veeson** [comment]
@lmk123 根据字母的驼峰写法自动分词进行翻译这个功能普通用户可能用不上，主要是程序员使用，所以建议作者单独做这个功能，设置成一个选项，然后给需要的程序员选择。

**Comment by lmk123** [comment]
后续同步至 #395
