### ISSUE TITLE
v7.0 开发计划

### ISSUE THREAD

**Issue by lmk123** [Selection-Translator/crx-selection-translate#185]
自 v6.1.2 后，划词翻译的开发已经搁置大半年了。现在我准备抽出时间解决累积起来的 [issues](https://github.com/Selection-Translator/crx-selection-translate/issues)，但 v6.x 的代码我又双叒叕看不下去了，所以准备再重写一次。

重写划词翻译是一个比较大的工程，所以我制定了一个计划表，按照顺序进行开发。计划表将会实时更新当前开发进度。
### 第一阶段：重构相关项目
- [x] [chrome-call](https://github.com/Selection-Translator/chrome-call)
- [x] [chrome-env](https://github.com/Selection-Translator/chrome-env)
- [x] [connect.io](https://github.com/Selection-Translator/connect.io)
- [x] [translation.js](https://github.com/Selection-Translator/translation.js)

我会先简单重构一下上面这些基础项目，包括但不限于：
- 使用新的 workflow
- 使用 [standardjs](http://standardjs.com/) 代码风格并加入 eslint
- 审查代码并适当优化
### 第二阶段：实现基本功能
- [ ] 内容脚本
- [ ] 后台脚本
- [ ] 弹出页
- [ ] 设置页
- [ ] 整合

这一阶段将会实现划词翻译现有的功能。可能会删除一些功能（例如网页翻译）。新版划词翻译会在 [next 分支](https://github.com/Selection-Translator/crx-selection-translate/tree/next)内开发。
### 第三阶段：解决 issues
- [ ] 解决部分 issues

新版划词翻译将会优先解决 bug 及部分功能改进的 issues。其他 issues 将会在后续的维护过程中逐一解决。
### 第四阶段：自动化测试
- [ ] 编写完自动化测试

以前划词翻译完成了全部代码的单元测试，但新版可能不会对业务类型的代码进行单元测试。
### 第五阶段：内部测试
- [ ] 完成内部测试

我会将新版划词翻译以私有的方式发布在 Chrome 网上应用店中，并邀请部分用户进行测试。

内测时间预计持续一个月左右，会视情况微调。
### 第六阶段：小范围发布
- [ ] 小范围发布之后没有收到 issue 了

新版划词翻译会先发布给 5% 的用户使用，以免没有测出来的 bug 影响所有用户。
### 第七阶段：全面发布
- [ ] 全面发布新版划词翻译

新版划词翻译发布给所有用户使用，开发计划结束。

**Comment by czmecho** [comment]
能否提供一个选项。当主动在扩展输入中文的时候，自动翻译为英语（或其它预设的语言）。
这样用户不必再将目标语言（默认中文）改为英文。

**Comment by lmk123** [comment]
@czmecho 目前只有谷歌翻译不会自动将中文翻译成英文。我会改进这一点的

**Comment by GavinAndre** [comment]
希望能增加这个功能：根据字母的驼峰写法自动分词进行翻译

**Comment by Veeson** [comment]
@lmk123 @GavinAndre 根据字母的驼峰写法自动分词进行翻译这个功能普通用户可能用不上，主要是程序员使用，所以建议作者单独做这个功能，设置成一个选项，然后给需要的程序员选择。

**Comment by orangebook** [comment]
+1

**Comment by lmk123** [comment]
https://github.com/Selection-Translator/crx-selection-translate/projects/4
