### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jokermonn** [Selection-Translator/crx-selection-translate#191]
您好，首先感谢你的无私奉献给我们带来了这么好的插件。想提一个意见，就是更改翻译的来源（百度翻译，必应翻译，有道翻译）之后，我希望这个插件能记住我的选择，而不是每次都是默认百度翻译。比如这次我选择了有道翻译，我希望下次依然是有道翻译。讲真，感觉百度翻译比有道和必应差了蛮多的，您可以考虑设置一下默认的翻译不是百度翻译

**Comment by li4599179** [comment]
朗读功能能够设置语速么

**Comment by lmk123** [comment]
@li4599179 不能。

另外，不相关的问题请新开一个 issue

**Comment by spiritedRunning** [comment]
有同样的问题，希望能添加一个设置选项，能够设置默认使用什么翻译来源。现在的用起来很麻烦啊

**Comment by lmk123** [comment]
#304 新版将会同时显示多个翻译结果，所以这个问题也不存在了。
