### ISSUE TITLE
给弹出窗口增加关闭按钮

### ISSUE THREAD

**Issue by czmecho** [Selection-Translator/crx-selection-translate#192]
有时候浏览网页，不小心按到触控板，然后弹出翻译，但却不会自动消失，只能刷新页面。

**Comment by lmk123** [comment]
确实会有这种情况。

如果你想知道原因的话——这可能是因为你当前的网页里有一个 `<iframe>`，当你选中 iframe 内的文字时，iframe 内的翻译按钮会弹出，然后当你点击 iframe 外的网页时，iframe 内的翻译按钮是不知道外部点击了网页的。

**Comment by Fszer** [comment]
@lmk123 
我有个建议就是给弹出窗口添加一个显式关闭按钮，那么在这种情况下可以手动的关闭掉了

**Comment by chermy** [comment]
嗯, 这个问题现在还在. 建议和上面一样.

**Comment by lmk123** [comment]
后续同步至 #495
