### ISSUE TITLE
内容过多时显示滚动条

### ISSUE THREAD

**Issue by veeson** [Selection-Translator/crx-selection-translate#205]
感觉这款翻译插件很不错，感谢作者的用心付出，使用过程中也发现还是有优化的空间的，比如弹出框有时会卡顿，甚至是直接是弹不出来这样子，真心希望作者有时间的话能定期更新一下，谢谢！

**Comment by lmk123** [comment]
因为懒 😂

**Comment by Veeson** [comment]
好吧😯 ------- > >
> 不过还是给点改进建议吧，比如弹出框延时甚至直接不能弹出的问题，当用户要选中的翻译文本超过200个字符的话能不能直接调用百度翻译接口，而不需要用户去手动去选择，还有如果用于显示返回的翻译结果的显示框过长的话能不能考虑实现滚动，而不是像现在这样铺满上下整个屏幕，而且如果显示框超过整个屏幕的话超出的内容就没法查看了，虽然很少有用户要选中大量的文字以至于翻译的结果超出整个屏幕，但这应该也算是一个bug吧。暂时先想到这些问题，以后在补充吧。希望作者再接再砺，再出新版😂
