### ISSUE TITLE
网页翻译无法使用

### ISSUE THREAD

**Issue by jiangbeth** [Selection-Translator/crx-selection-translate#206]
用的chrome浏览器，管怎么办

**Comment by lmk123** [comment]
我这边在 https 下是能正常使用的，你能具体描述下你是在哪个网址下无法使用哪个功能吗？

**Comment by jiangbeth** [comment]
您的反映好迅速啊
https://torrentfreak.com/pirate-bay-king-torrents-160814/      微软根本没反应，以下截图是有道和google translate的，打扰了，多谢啊！
![qq 20160815104133](https://cloud.githubusercontent.com/assets/8001330/17654386/36490696-62d5-11e6-8a2f-fce5b6140ecf.jpg)
![qq 20160815103727](https://cloud.githubusercontent.com/assets/8001330/17654385/363c1238-62d5-11e6-8f84-4266b07065a9.jpg)

**Comment by lmk123** [comment]
我懂了，你指的是网页翻译功能。

网页翻译确实有很多问题，这部分功能不是划词翻译实现的，划词翻译仅仅是引用了这些翻译网站提供的网页翻译代码，我准备在下个版本中将这个功能删除了。。

单词翻译的音标目前只有“有道翻译”才能提供，如果其他翻译引擎有一天也提供了，我也会加上来的。

**Comment by jiangbeth** [comment]
好的多谢

**Comment by lmk123** [comment]
网页翻译已经不计划集成在划词翻译中了。
