### ISSUE TITLE
content.js:1Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by jy1989** [Selection-Translator/crx-selection-translate#219]
出现大量这个错误
貌似chrome更新后就有这个错误了
chrome版本  版本 53.0.2785.116 (64-bit)
划词翻译版本 当前版本：v6.1.2， 已是最新版本。
请修复一下

**Comment by lmk123** [comment]
我的 Chrome 版本是 53.0.2785.143，但没有你这个问题。

更新一下浏览器之后再试试？

**Comment by jy1989** [comment]
@lmk123 
已更新为   版本 53.0.2785.143 (64-bit)
问题还存在
![image](https://cloud.githubusercontent.com/assets/1291756/19226759/4ef5b138-8ee2-11e6-9c7f-b17808cba771.png)

![image](https://cloud.githubusercontent.com/assets/1291756/19226767/5d7e9404-8ee2-11e6-9a69-4754e918b45c.png)

我的系统是macOS 10.12

**Comment by lmk123** [comment]
我的系统是 macOS 10.11.6，不过 Chrome 插件的问题更操作系统应该没多大关系。

你可以试试只启用划词翻译，看看是否还会出现这个错误

**Comment by lmk123** [comment]
可能与 #228 有关

**Comment by asins** [comment]
![image](https://cloud.githubusercontent.com/assets/898354/20256168/b1af0616-aa7c-11e6-93fa-a015b8cb3eff.png)

我的系统: macOs v10.12.1 
chrome版本 56.0.2908.0 canary (64-bit)

常出现这样的问题，

比如打开https://github.com/krasimir/absurd/blob/master/lib/processors/html/helpers/TemplateEngine.js这个地址，再打开开发人员工具，在从开发人员工具中将鼠标移动到网页中就会报这错误。经常报这个错误。

**Comment by lmk123** [comment]
@asins 按照你的步骤，我这里仍然没法重现 😂

**Comment by asins** [comment]
怎么可能没问题，
上面反馈的 chrome v56版是chrome canary，我再拿chrame V54.0.2840.87 (64-bit)测试，已经关闭其它所有插件并重启chrome后问题还是一样的。

退一步说，不能重现也请处理下这个报错，反馈这问题的人员也不少噢。
![image](https://cloud.githubusercontent.com/assets/898354/20257830/2bb38f40-aa87-11e6-8dc8-e1f785405c36.png)
![image](https://cloud.githubusercontent.com/assets/898354/20257844/3ab69e74-aa87-11e6-95b7-d7de1842f73c.png)

**Comment by lmk123** [comment]
我看了一下，已经可以确认跟 #228 是重复的问题了，所以这个 issue 我就关闭了。
