### ISSUE TITLE
翻译显示UI界面可否改善一下

### ISSUE THREAD

**Issue by yohole** [Selection-Translator/crx-selection-translate#220]
目前划词翻译弹出的翻译显示占用网页空间过大，ＵＩ界面相关样式与颜色有点难看，可否参考一下设置一下灰白色，略显透明？

**Comment by lmk123** [comment]
我在设计方面并没有很多经验 😂

**Comment by xiecg** [comment]
@lmk123 

非常棒的翻译插件，原来是 ele.me 的FE。

界面可以参考百度的翻译，比较简洁。图标的线条细一点就差不多了。

**Comment by lmk123** [comment]
@xiecg 谢谢你的建议，我正在开发新版划词翻译，已经计划会改善 UI 了

**Comment by lmk123** [comment]
新版本已经计划改进界面了
