### ISSUE TITLE
哈哈，很多人提议修改翻译界面啊，我也墙裂建议啊

### ISSUE THREAD

**Issue by xshrim** [Selection-Translator/crx-selection-translate#222]
1、翻译界面UI太扎眼，色调有点深。
2、界面上下两块绿色的太宽了，其实完全可以非常窄的。
3、界面的位置可不可以改为可以设置的，在下方有点尴尬啊，一来挡住了后续的文字，二来有些别的扩展比如划词显示搜索菜单之类的会互相遮挡了（比如有个selection search插件），所以建议能设置在下方还是上方显示，方便和其他插件一起使用。

另外我觉得有个翰林英汉双解词典的插件在翻译界面上有个more的功能，挺好的，直接在当前页打开词条的详细详细，希望划词翻译可以借鉴一下。
真心希望划词翻译越做越好^^

**Comment by lmk123** [comment]
界面的建议我很喜欢 😄 

“more” 的功能也是有的，点击右下角的 “via XX翻译” 就是

**Comment by xshrim** [comment]
不一样，more的是词典，有详细的词条内容，包括例句，同反义词，其他词典解释等等。
而via则是翻译，只是一个翻译界面，内容还不如小弹窗丰富，感觉没用啊。
我觉得翻译界面下面可以分成两部分，一部分点击可以跳转到在线翻译页面（针对选中的不是单个词条的情况），另一部分点击则可以跳转到某个在线词典的词条页面（针对选中的是单个词条的情况。在线词典可以用有道，必应，海词等等，尤其是海词词条内容很丰富），这两部分的实现逻辑应该是一样的。
再灵活点可以让用户在设置界面自己选择在线翻译和在线词典，直接不要via XXX，这样一来强大不少啊。
貌似要求有点多。。。。请原谅我的强迫症。。
期待您的完善！！！

**Comment by huangjinqiang** [comment]
建议划词的窗口尽量接近采用纸质颜色，边框默认隐藏相关UI组件

**Comment by giuem** [comment]
建议增加自定义样式的功能

**Comment by xinnix** [comment]
建议增加自定义样式，配置页可以直接留css接口

**Comment by yumenkun** [comment]
没好的方案不如就像google翻译那样简洁风格 白底算了，都比现在好

**Comment by lmk123** [comment]
新版本已经计划改进界面了
