### ISSUE TITLE
Google翻译API参数问题

### ISSUE THREAD

**Issue by chengzhoukun** [Selection-Translator/crx-selection-translate#223]
Google翻译网页版的接口形式是：
https://translate.google.cn/translate_a/single?client=t&sl=zh-CN&tl=en&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=1&tk=602240.1012272&q=%s
其中client参数对翻译效果影响最大，client=t, client=at, 结果一样，但client=at不需要tk参数验证，
效果应该比client=gtx的质量好

**Comment by lmk123** [comment]
你的链接打开之后显示的是 403

**Comment by lmk123** [comment]
无反馈，我就先关闭了。
