### ISSUE TITLE
部分网页 划译 一直显示off 状态

### ISSUE THREAD

**Issue by suxilong** [Selection-Translator/crx-selection-translate#224]
部分网页 划译 一直显示off 状态
例如 http://www.freertos.org/Embedded-RTOS-Queues.html
        https://e2e.ti.com/support/embedded/tirtos/f/355/t/550188

等等，，，

**Comment by suxilong** [comment]
就连 知乎  也是一直显示off 态

**Comment by lmk123** [comment]
我在这些网站里都是可以正常使用划词翻译的。会不会是你的“域名筛选“的设置有问题？

**Comment by errorlife** [comment]
http://www.cnblogs.com/yangxia-test/p/4123155.html
给你们看看什么叫做完美重现。

**Comment by lmk123** [comment]
@errorlife 
<img width="728" alt="wx20161214-183829 2x" src="https://cloud.githubusercontent.com/assets/5035625/21178916/9ce44cc4-c22c-11e6-953e-77b01476a83f.png">

**Comment by bugss** [comment]
@errorlife   http://www.cnblogs.com/yangxia-test/p/4123155.html 
github 是https也可以
这个网页我也可以用.
但是
https://developer.wordpress.org/themes/getting-started/what-is-a-theme/
这个http的也不行.
http://www.w3school.com.cn/php/func_misc_define.asp
等等网站不行.
http://localhost:8081/blog/ 
这个也不行

**Comment by bugss** [comment]
... 我发现重启chrome之后就可以用了.   看看其他人是不是也是这个情况
