### ISSUE TITLE
是否可以添加生词本功能

### ISSUE THREAD

**Issue by youdonghai** [Selection-Translator/crx-selection-translate#225]
是否可以考虑添加一个生词本功能，让用户可以把生词加入生词本，例如有道生词本。

看到另外一个作品在谷歌翻译的基础上加入了有道生词本。
https://github.com/cclient/chrome-extensions-googletranslatewithyoudaowordnote

**Comment by lmk123** [comment]
有很多人都希望能加生词本功能，我会把这个新功能加入到开发计划中的。

**Comment by ShumRain** [comment]
+1

**Comment by gs1223** [comment]
+1！跪求有道单词本

**Comment by diandengs** [comment]
什么时候支持呢？

**Comment by lmk123** [comment]
#242 已经计划实现一个历史记录的功能
