### ISSUE TITLE
【划词翻译】与【163邮箱部分冲突】

### ISSUE THREAD

**Issue by qiseniguang** [Selection-Translator/crx-selection-translate#226]
问题描述：
我们学校用163邮箱发通知，我们学生需要经常到邮箱里下载，通知的格式一般为pdf格式，也有压缩包格式和其他office文件格式。

当不启用插件的时候，将鼠标移到邮箱附件栏的文件上，会自动出现悬浮窗，此时点击下载，文件就会下载到电脑上。
[单击查看图片](http://photo.weibo.com/1771050182/wbphotos/large/mid/4037116646800052/pid/699014c6jw1f9cxjxfgj9j20ca08fjrz)

当启用插件的时候，将鼠标移到邮箱附件栏的文件上，会自动出现悬浮窗，此时点击下载，如果要下载的文件是pdf，那么没有任何反应，如果是其他文件，正常下载。

并且
按F12查看Console会报错，似乎是和chrome自带的pdf阅读插件冲突。
即使在网页上禁用划词翻译也依旧会冲突。

**Comment by lmk123** [comment]
这是一个已知的 bug：#183
