### ISSUE TITLE
chrome canary 报错 'pageX' of undefined

### ISSUE THREAD

**Issue by yyjazsf** [Selection-Translator/crx-selection-translate#228]
❌chrome canary 浏览器，经常报下面的错误。

### 重现：
比如 在 [translate.google.cn](https://translate.google.cn)
打开开发者工具，改变 开发者工具的  大小。

或者使用gulp 、webpack 的情况下

```
content.js:1 Uncaught TypeError: Cannot read property 'pageX' of undefined
    at b (content.js:1)
    at E (content.js:1)
    at m (content.js:1)
    at K.setEventXY (content.js:1)
    at K.pointerMove (content.js:2)
    at HTMLDocument.<anonymous> (content.js:1)
```

**Comment by lmk123** [comment]
可能跟 taye/interact.js#251 有关系，不过下个版本不准备用 interact.js 了，所以可能不会再有这个问题了。

**Comment by yyjazsf** [comment]
so,close this issue?

**Comment by lmk123** [comment]
先放着吧，我抽空看看。

**Comment by xlqstar** [comment]
现在chrome更新到了55，这个问题全面爆发啦！~我之前没注意到这个issue，原来这个问题很早就开始了~

**Comment by win7killer** [comment]
是哦，chrome55  必现，该修了

**Comment by lmk123** [comment]
我升级到 Chrome 55 之后总算看到这个错误了 😂

**Comment by lmk123** [comment]
大家升级到 6.1.3 之后就不会看到错误消息了。

**Comment by lmk123** [comment]
Hi 各位，由于我的疏忽，v6.1.3 版会导致网页的错误也被隐藏了，请升级到 v6.1.4 避免受到影响 😂
