### ISSUE TITLE
划词翻译语言不会自动选择

### ISSUE THREAD

**Issue by q856070** [Selection-Translator/crx-selection-translate#229]
选择谷歌翻译时，划词翻译不会自动把中文翻译成功英文，需要多点一步目标语言选择为英文才能翻译，强烈建议修改，因为该功能在有道翻译上是会自动翻译的

**Comment by lmk123** [comment]
重复 #146

**Comment by q856070** [comment]
感谢，希望早日更新😂

**Comment by whenYouAreOld** [comment]
遇到类似问题，建议增加默认选择的按钮，选择默认由A语言翻译为B语言
