### ISSUE TITLE
为什么网页翻译不加上百度翻译的选项呢？

### ISSUE THREAD

**Issue by momosu** [Selection-Translator/crx-selection-translate#230]
有技术问题吗？

**Comment by lmk123** [comment]
划词翻译提供的网页翻译功能都是网上现成的网页翻译功能的，例如[有道网页翻译](http://fanyi.youdao.com/web2/)、[必应网页翻译](http://www.bing.com/widget/translator)与[谷歌网页翻译](http://translate.google.com/manager/website/?hl=zh-CN)，但是我没有找到百度翻译提供网页翻译功能。

**Comment by lmk123** [comment]
实际上，这些网页翻译功能并不是划词翻译的功能，并且总是不稳定，所以下个版本决定将网页功能删除了。
