### ISSUE TITLE
有道翻译没有返回有效的翻译结果，请稍后重试。？

### ISSUE THREAD

**Issue by logig** [Selection-Translator/crx-selection-translate#231]
![image](https://cloud.githubusercontent.com/assets/15779888/20296599/cc7ac50a-ab46-11e6-8a64-fd23a2ed0ff0.png)

-----
有时候会这样，所有单词都没有翻译结果，是网络的问题吗？

为什么只有有道翻译可以显示音标？要不我就用百度翻译了。

**Comment by lmk123** [comment]
有道翻译偶尔确实会出现这样的问题，但次数不多。

只有有道翻译的接口提供了音标，如果其他翻译接口日后也提供了音标，我会加上的。
