### ISSUE TITLE
最好用的翻译扩展，但是为什么点击顶部菜单扩展图标打开“翻译盒子”的时候会卡，感觉比大多数扩展弹出的速度都慢啊。。。

### ISSUE THREAD

**Issue by meatlab** [Selection-Translator/crx-selection-translate#232]
大佬 这个弹出面板会卡是哪个功能导致的啊？ 试过很多翻译扩展，就你这个最好用了，除了弹出速度慢以外。。。
另外，配合ctrl的划词翻译，能让“按ctrl键”在划词前后都起作用吗？因为以前其他一些扩展是这样设置的我感觉很好用，而且现在的设置快捷键功能没法只设置ctrl一个键

再次感谢做出这么好用的扩展:)

**Comment by lmk123** [comment]
我正在着手开发新版的划词翻译，弹出窗口慢的情况我会优化的。

至于 Ctrl 的问题，我觉得多按一个键少按一个键没啥不同啊 :joy:

**Comment by Licheng-Xu** [comment]
我也是，之前挺正常，现在好卡

**Comment by meatlab** [comment]
期待新版，能换个icon就好了😂

**Comment by 10100010110000101010** [comment]
可能是在检查新版本？这完全没有用吧
![image](https://cloud.githubusercontent.com/assets/22018718/23049464/47106000-f4f7-11e6-8477-710382774b82.png)

**Comment by lmk123** [comment]
#169
