### ISSUE TITLE
网站过滤不生效

### ISSUE THREAD

**Issue by punkmonday** [Selection-Translator/crx-selection-translate#233]
我设置了几个不需要翻译的网站域名,但是划词翻译依然会生效,导致翻译界面遮盖掉需要点击的按钮而无法正常浏览网址

**Comment by lmk123** [comment]
能列举一下屏蔽了哪些网站域名不会生效吗？

**Comment by punkmonday** [comment]
常规的网站,我点击[已对当前网站启用]之后切换为[已对当前网站禁用]这个功能可以使用,
是点击设置进去里面的域名筛选v.6.0.0新增那里设置的域名都不生效,而且chrome扩展图标没有变为off
你可以尝试baidu.com

**Comment by lmk123** [comment]
我刚才尝试在设置里添加 `baidu.com`，然后我打开百度之后，扩展图标正常显示了 `off` 并且在百度里划词没有弹出按钮。

你能提供一下你使用划词翻译的环境吗？例如操作系统、浏览器版本号、划词翻译版本号之类的。

**Comment by punkmonday** [comment]
OS:win7
browser:chrome  54.0.2840.99
划词翻译版本:V6.1.2
你试试先用按钮将baidu.com改为[已对当前网站启用](on状态)
然后再在选项里添加域名过滤,这两个功能有冲突,点击[已对当前网站启用](on状态)之后,
即使你已经设置了此网站过滤,仍然会生效.

**Comment by lmk123** [comment]
如果你首先将 `baidu.com` 添加进了“域名过滤”列表，然后再把一个百度页面改为“已对当前网站启用”，那么划词翻译会自动将“过滤列表”里的 `baidu.com` 删除，所以实际上所有以 `baidu.com` 结尾的域名都被启用了。

举例来说，你将 baidu.com 添加进了域名过滤列表，然后把 www.baidu.com 改为“已对当前网站启用”，此时你在 zhidao.baidu.com 里划词时，翻译按钮也是会弹出来的。

这部分功能确实设计的不够好，目前我正在开发新版本 v7.0，这部分功能我会重新设计一下的，例如支持 `*.baidu.com` 的过滤语法、黑名单白名单模式等。

**Comment by lmk123** [comment]
#259
