### ISSUE TITLE
点击图标能否不翻译复制的文本(建议)

### ISSUE THREAD

**Issue by Jaggle** [Selection-Translator/crx-selection-translate#234]
有时候我点击这个按钮时是因为网页上面存在无法选取的文本，比如图片，或者视频中的文字，所以我想直接输入翻译，但是由于剪切板中存在复制的内容，所以就被自动粘贴进去了，需要我先删掉再输入自己想要翻译的内容。

建议: 添加一个设置选项，可以手动设置是否需要自动复制剪切板中的内容。

冒昧的PS: 你这个按钮确实影响美观啊，有打算换图标么。。。

**Comment by lmk123** [comment]
选项里有一项设置“打开翻译盒子时，自动翻译剪切板内的文本”，你把它取消勾选就好了

PS: 图标打算换成这个：
https://github.com/Selection-Translator/crx-selection-translate/issues/93#issuecomment-177447239

**Comment by Jaggle** [comment]
原来如此，感谢，当时我看了两遍怎么没看到这个选项呢，好眼瞎
PS:图标比目前的好看多了
