### ISSUE TITLE
console不停地跳 Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by xlqstar** [Selection-Translator/crx-selection-translate#237]
好烦躁啊，强迫症的我很讨厌终端里一大票这个错误提示啊！！
![image](https://cloud.githubusercontent.com/assets/2224956/20997298/26f87c34-bd3f-11e6-9acb-bbc972553bb8.png)

**Comment by lmk123** [comment]
重复 #228
