### ISSUE TITLE
chrome浏览器使用划词翻译(即时显示,不显示划词盒子)翻译界面不会消失

### ISSUE THREAD

**Issue by punkmonday** [Selection-Translator/crx-selection-translate#238]
broswer: chrome
version:  54.0.2840.99 m 
description:
划词即时显示结果之后,窗口会一直滞留在页面上,再做其他操作的时候,比如看视频,就会被翻译界面遮挡.
只有重新刷新页面之后,窗口才会消失.

**Comment by lmk123** [comment]
是不是点击了左上角的图钉，让翻译窗口固定住了？

**Comment by punkmonday** [comment]
没有，我特意点了pin测试了，可能只是在chrome 54这个版本出现，firefox我没有进行测试

**Comment by punkmonday** [comment]
今天又测了下，发现是一直卡在正在查询，请稍后，但是一直没返回结果，导致卡顿，然后就不会消失
访问的页面是wikipedia,用的VPN，可能和VPN有关

**Comment by lmk123** [comment]
是的，正在加载时窗口是不会消失的，但过了5秒还没有结果的话就会显示已超时，这时就会隐藏了。

你可以更改一下你的 VPN 配置，让它在访问国内网站的时候不要走代理。

**Comment by punkmonday** [comment]
ok,十分感谢~
