### ISSUE TITLE
Bing和Google,Goole国内的朗读功能无效

### ISSUE THREAD

**Issue by tiandian** [Selection-Translator/crx-selection-translate#239]
非常好的一款翻译软件,  目前发现有个小问题, 就是Bing和Google,Goole国内的朗读功能经常无效.

打开这个页面http://www.zdnet.com/article/2016s-five-best-internet-media-streaming-devices/,
Bing和Google,Goole国内的中英朗读功能均无效,

打开这个页面http://www.phoronix.com/scan.php?page=home,
Google,Goole国内英文朗读功能有效效, 中文朗读功能无效.

打开其它英文站点朗读功能基本上也无效.

**Comment by lmk123** [comment]
我这边是正常的，可能是你的网络不稳定造成的。
