### ISSUE TITLE
插件会屏蔽部分js报错

### ISSUE THREAD

**Issue by itbeihe** [Selection-Translator/crx-selection-translate#243]
在vue的webpack项目中，引用一个不存在的模块，不会报模块错误，最初我以为是vue的问题。
https://github.com/vuejs/vue/issues/4637
在vue提issue后，排查不是，怀疑可能插件导致的，挨个关闭插件，发现是本插件的问题。

**Comment by lmk123** [comment]
确实会有这个问题，起因是因为 #228，为了不让控制台不断的报错，我屏蔽了来自 interact.js 的错误（见 b25ec7d），这只是一个临时的解决方案，目前 interact.js 好像已经修复了这个 bug，我这就试试看。

**Comment by lmk123** [comment]
升级至 v6.1.5 就不会有这个问题了。

**Comment by itbeihe** [comment]
谢谢
