### ISSUE TITLE
界面无法关闭

### ISSUE THREAD

**Issue by yuanwow** [Selection-Translator/crx-selection-translate#244]
有时网络不太好的时候会一直卡在这个界面 也无法关闭   只有刷新才能消除
![default](https://cloud.githubusercontent.com/assets/8564241/21639701/5a412294-d2ac-11e6-9bd6-2c58193377ef.PNG)

**Comment by lmk123** [comment]
查询中的时候界面是无法关闭的，但如果5秒内还没有查询结果就会显示“查询超时”，之后就可以关闭了
