### ISSUE TITLE
v6.2.1开启PDF功能，仍然不能划词翻译

### ISSUE THREAD

**Issue by onloner2012** [Selection-Translator/crx-selection-translate#247]
使用pdf.js的Chrome插件打开PDF，开启PDF划词翻译仍然不能翻译，求解救。

**Comment by lmk123** [comment]
具体是哪个网址的 PDF 不能翻译？

**Comment by onloner2012** [comment]
不是网站的pdf，是本地的pdf，而且，我发现，有些pdf不能划词，可能是ocr的问题，有些pdf却是可以的。你的插件做的真的好，我最近也在学习js，如果有可能，可以贡献部分代码，不过还是初学阶段。

**Comment by amosbird** [comment]
@lmk123 我也遇到了这个问题（在线pdf），[例子](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf)，不过我是自己编的pdfjs。我测了1.6和1.7版本的都不行，chrome store里的可以。

**Comment by lmk123** [comment]
你所说的 PDF.js 的插件是指这个 [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) 吗？

如果你安装了这个插件，那么划词翻译确实是没法划词的，因为 PDF Viewer 将 pdf 文件重定向到了它扩展内部的页面，但是划词翻译的代码是没法注入到别人扩展里面去的。

**Comment by amosbird** [comment]
@lmk123 store里的PDF viewer可以的啊 ![](https://ptpb.pw/MDlR.jpg)

**Comment by lmk123** [comment]
@amosbird 看看你的地址栏的地址是以什么开头的。
 chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/ 开头说明是用 Chrome Store 里的 PDF Viewer 扩展打开的，此时是无法翻译的

chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/ 开头说明是用划词翻译内置的 PDF Viewer 打开你的 pdf 的，此时是可以翻译的

**Comment by amosbird** [comment]
@lmk123 我把自己的pdfjs编到划词里，现在好了。谢谢
