### ISSUE TITLE
能不能将lookup.js:97的console.log去掉呢

### ISSUE THREAD

**Issue by heekei** [Selection-Translator/crx-selection-translate#253]
能不能将lookup.js:97的console.log去掉呢？每次开发的时候选中东西一直输出，好忧伤啊

**Comment by heekei** [comment]
自己动手丰衣足食，自己手动删了

**Comment by heekei** [comment]
自己动手丰衣足食，自己手动删了

**Comment by lmk123** [comment]
划词翻译的项目里面并没有 lookup.js 啊？

**Comment by heekei** [comment]
![image](https://cloud.githubusercontent.com/assets/10609199/23442951/b7645258-fe66-11e6-97bc-1c2d36bd911c.png)
@lmk123

**Comment by lmk123** [comment]
你确定这是划词翻译么？划词翻译的版本现阶段是 6.2.1 啊

**Comment by lmk123** [comment]
而且，以前版本的划词翻译从来没有过这些文件。

**Comment by lmk123** [comment]
你这个扩展是[有道词典chrome鼠标取词插件](https://chrome.google.com/webstore/detail/aohddidmgooofkgohkbkaohadkolgejj)吧，不是划词翻译，你走错地方了。

**Comment by heekei** [comment]
这就尴尬了，原来这个是有道词典的chrome插件，我忘了我chrome上居然还多装了个有道的，【手动尴尬脸】

**Comment by heekei** [comment]
哈哈哈，我以为我chrome上只有一个“划词翻译”
