### ISSUE TITLE
谷歌翻译 和 谷歌国内, 当内容中有 & 符号时, 后面的内容就不会显示. 

### ISSUE THREAD

**Issue by chermy** [Selection-Translator/crx-selection-translate#254]
![1](https://cloud.githubusercontent.com/assets/5954008/23606520/104933b4-029c-11e7-9c6c-9c21bb42c2ee.png)
我用的是6.2.1
64位
应该是文字& 和 Url的参数符号& 冲突了.

**Comment by chermy** [comment]
@lmk123 发几个测试连接: http://clickandcarry.com/  https://www.amazon.com/dp/B00V5IMLQW  https://www.tripadvisor.ca/ShowTopic-g187890-i418-k6788295-Easy_Jet_Hold_Baggage_Carry_On_Questions-Palermo_Province_of_Palermo_Sicily.html  http://www.spicers.ca/shop/  你可以测试一下看看. 谷歌和谷歌国内都有问题.

**Comment by lmk123** [comment]
感谢反馈

**Comment by lmk123** [comment]
#286
