### ISSUE TITLE
请求未成功会进入假死状态

### ISSUE THREAD

**Issue by karlind** [Selection-Translator/crx-selection-translate#256]
当在查询的时候如果请求没有及时返回结果（其他原因？）会处于假死状态，一直显示`正在查询，请稍候……`，点击也没有任何反应，应该是阻塞了，只能重新刷新页面才能解决。

可以在请求的时候加一个`timeout`， 或者在查询的时候同时监听鼠标动作，点击页面的话就取消查询，应该可以有效解决阻塞问题。

**Comment by karlind** [comment]
那应该是超时没有其作用，也出现过`查询超时`，但是到现在为止只出现过1,2次，大部分情况下都是处于阻塞状态。应该是出现了bug。

**Comment by lmk123** [comment]
能提供一下可以重现这个 bug 的步骤吗？例如在哪个网页划词时会出现这样的问题

**Comment by karlind** [comment]
在 [Spring documentation](docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/) 里面我遇到过很多次，任何单词都有可能出现，同一个单词有时候出问题也有时候不出问题

**Comment by lmk123** [comment]
没法重现，我觉得这可能跟网络环境有关

**Comment by karlind** [comment]
我重现了，确实和网络有关。在网络已经连接，但是无法访问网络的时候（比如网络环境很差，WiFi信号弱），就会出现这个问题。

**Comment by karlind** [comment]
在这种情况下，`timeout`没有起作用？

这个bug估计遇到的人可能比较少，但是我发现我经常会遇到，而且我用这个插件也很频繁，所以如果能修复一下这个bug的话就太棒了：D

**Comment by lmk123** [comment]
我会尝试重现这个问题的，如果重现就会修复 :)

**Comment by karlind** [comment]
那就太棒了，谢谢了。这个插件真的是很好用啊

**Comment by lmk123** [comment]
后续同步至 #515
