### ISSUE TITLE
没看到捐助链接呢？

### ISSUE THREAD

**Issue by xiaoyaoyou** [Selection-Translator/crx-selection-translate#261]

**Comment by lmk123** [comment]
在这 https://github.com/Selection-Translator/crx-selection-translate/wiki/捐助划词翻译

确实藏的很深，我一会儿把它放在首页

**Comment by xiaoyaoyou** [comment]
二维码图片都不全，钱多想捐点出去也是挺难的 -!-

**Comment by lmk123** [comment]
我在项目首页更新了支付宝和微信的二维码图片：https://github.com/Selection-Translator/crx-selection-translate#捐助划词翻译

或者，你可以直接转账到我的支付宝账号：milk.lee@qq.com

感谢捐助

**Comment by xiaoyaoyou** [comment]
你首页的两个二维码图片不全，没法扫

**Comment by lmk123** [comment]
打开这个链接试试？https://o93y1elkp.qnssl.com/xxxxxx.png

**Comment by xiaoyaoyou** [comment]
嗯，这个链接可以，我只是提醒下首页的二维码不了用哈-！-，捐助已直接转入你的支付宝，辛苦了

**Comment by lmk123** [comment]
已收到，感谢捐助

我猜二维码不见了可能是网络原因，也可能是 GitHub 把二维码给屏蔽了 😂

**Comment by xiaoyaoyou** [comment]
不是网络原因，img的src属性的的原图片就是有部分缺失的，但data-canonical-src这个属性的原图片是OK的，不知道是不是github屏蔽的，总之github是个神奇的网站

**Comment by lmk123** [comment]
是的，我在另一个项目里也遇到了这个问题：上面的“扫一扫”的字还在，但是二维码不见了。

奇怪的是在我的项目里，我自己和周围的人打开的时候都是有二维码的，所以我猜是 GitHub 针对部分用户屏蔽了二维码。。
