### ISSUE TITLE
默认翻译引擎怎么修改呀？

### ISSUE THREAD

**Issue by lei40251** [Selection-Translator/crx-selection-translate#264]
现在默认是百度，我想改为有道，我改了之后再翻译就又变回百度了，请问这个要怎么设置，没有找到设置项。

**Comment by fancyfine** [comment]
今天必应翻译没用了，在设置里面，右击这个插件的图标设置里面有

**Comment by lei40251** [comment]
解决了，谢谢，原来这个设置要等好久才能加载出来呀。。。

**Comment by lmk123** [comment]
要很久吗 😂 我这里怎么一点就打开了
