### ISSUE TITLE
[提个醒] Google 翻译已经支持国内使用

### ISSUE THREAD

**Issue by rosuH** [Selection-Translator/crx-selection-translate#265]
Google 翻译新版已经支持国内用户使用，无需科学上网。

这样插件是否需要相应调整？（提个醒

[附普通话宣传视频](http://weibo.com/tv/v/EC1PybCNb?fid=1034:a6bc1367bfd1e9f0f450305f8afdb1a3)

**Comment by lmk123** [comment]
棒！看来是要更新一波了

**Comment by fengxiaochuang** [comment]
Google国内自动检测语言不智能,没有有道翻译智能,不知道这个能不能优化,另外如果不能优化的话,能不能给个可以配置的default选项

**Comment by lmk123** [comment]
其实谷歌翻译（国内）用的就是谷歌中国翻译的接口，这个接口是不需要翻墙的。

谷歌翻译划中文翻译的也是中文的问题现在已经计划修复了。
