### ISSUE TITLE
google翻译没有音标

### ISSUE THREAD

**Issue by jackboys000** [Selection-Translator/crx-selection-translate#266]
google翻译没有音标

**Comment by lmk123** [comment]
[常见问题](https://github.com/Selection-Translator/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E4%B8%8D%E6%98%BE%E7%A4%BA%E9%9F%B3%E6%A0%87)
