### ISSUE TITLE
希望自定义划词目标翻译语言

### ISSUE THREAD

**Issue by zddewe** [Selection-Translator/crx-selection-translate#273]
很多时候划中文词是想知道英文单词的。也就是说，如果能auto detect soure language and  define the default target language.

这样就好了^_^。

**Comment by gggccc44** [comment]
划中文词默认是显示的英文啊。。。你试过没有啊？你把忽略中文的勾取消

**Comment by lmk123** [comment]
这个功能已经在开发计划中了：#291
