### ISSUE TITLE
PDF无法翻译

### ISSUE THREAD

**Issue by 1703011** [Selection-Translator/crx-selection-translate#274]
一直以来PDF翻译功能一直可以正常使用，一个月前突然无法使用了。PDF翻译功能以及打开，尝试重新安装也没有用。目前把PDF拖入Chrome内，地址栏就会显示实际文件在电脑上的地址，而不是划词翻译插件的信息。

**Comment by boyliuxiaopeng** [comment]
划词翻译要复制打开可以翻译哟

**Comment by boyliuxiaopeng** [comment]
直接划词不能出现，不可固定标签

**Comment by boyliuxiaopeng** [comment]
提示没有权限对当前页面操作

**Comment by 1703011** [comment]
不太明白你的意思。以前我一直是可以划词翻译的呀。不用复制

**Comment by boyliuxiaopeng** [comment]
你好，我也出现同样的情况，也就反映下这个。谢谢你的回复！
​况。就是在PDF页面插件显示OFF，提示此页面无权限

2017-05-15 21:22 GMT+08:00 1703011 <notifications@github.com>:

**Comment by Knight-Wu** [comment]
我也是提示没有权限, 勾选了 allow access  to file urls, 截图给你


![2017-05-24_111916](https://cloud.githubusercontent.com/assets/20329409/26385707/24618c0a-4074-11e7-805b-dab0a52c5773.png)

**Comment by 1703011** [comment]
看来我的情况和你们的还不太一样。你们可以看路径地址，你们的文件实际上还是用划词翻译的PDF Viewer打开的，而我的文件就是用Chrome自带的PDF浏览器打开的。
![jietu](https://cloud.githubusercontent.com/assets/4069144/26387094/e9a4936a-4018-11e7-99c0-f991adeb0e10.png)

**Comment by boyliuxiaopeng** [comment]
不知道怎么回事呢

2017-05-24 12:36 GMT+08:00 1703011 <notifications@github.com>:

**Comment by lmk123** [comment]
@1703011 下面这两个框框你勾上了吗？
 
![image](https://cloud.githubusercontent.com/assets/5035625/26434166/a1db5286-4139-11e7-8a66-b3a05270539b.png)

**Comment by 1703011** [comment]
.....我的锅。。我的问题解决了。。所以看起来是我不知道啥时候脑子抽风把“允许访问文件网址”的勾给去掉了。。
