### ISSUE TITLE
【建议】关于禁用某些域名

### ISSUE THREAD

**Issue by feimiao** [Selection-Translator/crx-selection-translate#276]
比如 https://todoist.com 这个网址下不希望其翻译，而在 https://support.todoist.com 下希望其能进行翻译，然而禁用域名（todoist.com）会将其整个相关都禁用~~~
因此是否可以考虑添加白名单选项呢？这样某些域名的子域名就可以使用了😀

**Comment by lmk123** [comment]
新版本中会对域名的黑/白名单做更细的划分，尽情期待~

**Comment by lmk123** [comment]
#259
