### ISSUE TITLE
查询过的词做记录

### ISSUE THREAD

**Issue by funkhua** [Selection-Translator/crx-selection-translate#277]
你好：
    我我用划词翻译有一段时间了，非常喜欢对我帮助很大。但是每次查词后只能自己做记录，我想有没有可能添加一个新功能可以把查询过的词做下记录，方便使用的人做汇总和复习。
                                                                                                                                                     谢谢！

**Comment by lmk123** [comment]
这个功能已经计划在新版本中实现了，尽情期待 :)
