### ISSUE TITLE
PDF 翻译功能所调用的PDF.js有取词bug

### ISSUE THREAD

**Issue by huntersnk** [Selection-Translator/crx-selection-translate#279]
具体现象为在PDF文件里，在行末尾或者开头进行双击取词时，会同时自动选中下一行或者上一行末尾的词，进而无法正确取出翻译想要翻译的词汇，只能通过按住左键拖拽，精确定位来划词选词（触摸板划词好痛苦），并且 PDF.js 的选择定位很不准，经常漂移移位。
基本都是 PDF.js 自身的 bug，看到有人提出了同样的问题在那边：[PDFbug](https://github.com/mozilla/pdf.js/issues/8408)

所以问题来了，请问开发者是否能考虑更换其它的 pdf 库来解决这个问题，是否有办法支持 chrome 自带的 pdf viewer 来取词？（它是选择无比精准没有双击选择 bug 的）

感谢 :)

**Comment by lmk123** [comment]
那么问题来了，除了 PDF.js 还有其它的 PDF 解析库吗 😂 

另外，Chrome 自带的 PDF Viewer 是没有办法 “hack” 进去的，所以……这个问题无解 😂
