### ISSUE TITLE
依赖无法完整下载问题。

### ISSUE THREAD

**Issue by theoneLee** [Selection-Translator/crx-selection-translate#284]
运行 npm i 安装项目依赖时。前面都正常下载。
但是到『开始下载 pdfjs-dist.zip 至 ./src/pdf-viewer/ 目录……』，命令行停止不动了。

**Comment by lmk123** [comment]
这个文件是从 https://github.com/Selection-Translator/crx-selection-translate/blob/master/build/install-pdf-viewer.js#L18 下载的，国内下载 GitHub 上的文件确实很慢，你可以在本地搭个代理来下载。
