### ISSUE TITLE
运行 npm run dev问题

### ISSUE THREAD

**Issue by theoneLee** [Selection-Translator/crx-selection-translate#285]
在下载完依赖后。
运行 npm run dev出现问题。
以下为命令行信息：
> @ dev D:\win\doSth\Aword\Aword_plugin\crx-selection-translate-master
> webpack --config build/webpack.dev.config.js

Hash: d30af23c9af38d128e95
Version: webpack 1.15.0
Time: 5743ms
                    Asset     Size  Chunks             Chunk Names
              commons1.js   239 kB       5  [emitted]  commons1.js
selection-translator.woff   3.6 kB          [emitted]
               bs-lite.js   3.9 kB       1  [emitted]  bs-lite
               content.js   611 kB       2  [emitted]  content
               options.js   244 kB       3  [emitted]  options
                 popup.js  21.9 kB       4  [emitted]  popup
                    bg.js   381 kB       0  [emitted]  bg
              commons2.js   727 kB       6  [emitted]  commons2.js
              commons3.js   855 kB       7  [emitted]  commons3.js
              bs-lite.css   132 kB       1  [emitted]  bs-lite
              options.css  2.01 kB       3  [emitted]  options
                popup.css  1.16 kB       4  [emitted]  popup
          commons1.js.css    22 kB       5  [emitted]  commons1.js
    + 481 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

到此就一直不动了。（保持了这个状态好几个小时，最后手动中断掉。）

**Comment by lmk123** [comment]
建议你先了解一下 [Webpack](https://webpack.js.org)
