### ISSUE TITLE
在使用谷歌翻译时，文本中包含#或&等符号会导致截断

### ISSUE THREAD

**Issue by aiqinxuancai** [Selection-Translator/crx-selection-translate#286]

**Comment by lmk123** [comment]
举个例子？

**Comment by aiqinxuancai** [comment]
Multiple language support with C#, VB, F# and modern constructs like generics, Language Integrated Query (LINQ), async support and more.

比如这句 在#那里截断 翻译结果是
![image](https://user-images.githubusercontent.com/4475018/27370615-ef12b484-568f-11e7-8f3b-4f6fac9d8f10.png)

**Comment by pk27602017** [comment]
希望这个功能能够快点改进.....

**Comment by lmk123** [comment]
我最近重写了划词翻译内的翻译核心代码，现在已经没有这个问题了。

新的代码会在发布新版划词翻译是使用。
