### ISSUE TITLE
有道API平台升级，无法获得keyfrom

### ISSUE THREAD

**Issue by jasohwang** [Selection-Translator/crx-selection-translate#290]
有道翻译API平台升级了，申请之后可以创建应用，但是不知道对应的keyfrom应该填哪个，无法使用了。

**Comment by lmk123** [comment]
多谢反馈，我会在近期更新扩展以支持新的 API 申请方式。

**Comment by qiyuey** [comment]
一个月过去啦，加油啊

**Comment by JamesMackerel** [comment]
新的有道智云好像是100块体验，体验完了就没有了，我觉得是不是应该放弃这个平台算了……

**Comment by lmk123** [comment]
@JamesMackerel 目前我的打算就是放弃有道官方接口，改为直接用有道网页翻译的接口了。

**Comment by lmk123** [comment]
已经在划词翻译的核心翻译模块 [translation.js](https://github.com/Selection-Translator/translation.js) 并计划用在新版中。
