### ISSUE TITLE
希望增加直接翻译粘贴内容

### ISSUE THREAD

**Issue by snsnsjsn** [Selection-Translator/crx-selection-translate#296]
我在一台台式机上设置快捷键ctrl+q后，可以直接翻译粘贴板里面的内容，但是，现在在我笔记本电脑却不行了，而且打不开选项，我卸载从商店重新安装后还是不行？？
是怎么回事呢？
台式机是win7，笔记本是win10，chrome是同步的。差不多最新版本59.

我在突然在台式机上发现这个功能真好，但是现在却不能复现？？？

比如现在点击了插件图标，没有任何反应，而右键又选项，打开后却什么选项都没有？？

![image](https://user-images.githubusercontent.com/11435527/27984984-6de1a5bc-6415-11e7-8a1d-eb7b52f6d023.png)
现在点击了没有任何反应

本来应该是这样的

![image](https://user-images.githubusercontent.com/11435527/27984998-932a48e2-6415-11e7-9077-f92cc0ae4475.png)
我设置ctrl+q或者点击插件图标后可以翻译粘贴板里面内容
现在弹不出框来。

是不兼容？？？

**Comment by lmk123** [comment]
这是一个已经确认的 bug，新版中会修复。
