### ISSUE TITLE
与pdf标记插件kami不兼容

### ISSUE THREAD

**Issue by weiwangthu** [Selection-Translator/crx-selection-translate#298]
当装上kami插件时，无法使用pdf翻译功能，出错信息如下：
此扩展程序无法将该网络请求重新定向到 chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=file%3A%2F%2F%2FE%3A%2F%25E5%258D%259A%25E5%25A3%25AB%2F%25E5%25AE%259E%25E9%25AA%258C%25E5%25AE%25A4%25E6%259D%2590%25E6%2596%2599%2F%25E8%2587%25AA%25E5%25B7%25B1%25E8%25A1%25A5%25E5%2585%2585%2F%25E8%25AE%25BA%25E6%2596%2587%25E5%2586%2599%25E4%25BD%259C%2Fown%2Fbare_conf.pdf，因为其他扩展程序（Kami - PDF and Document Markup）已将其重新定向到 chrome-extension://ecnphlgnajanjnkcmbpancdjoidceilk/content/web/viewer.html?source=extension_pdfhandler&amp;file=file%3A%2F%2F%2FE%3A%2F%25E5%258D%259A%25E5%25A3%25AB%2F%25E5%25AE%259E%25E9%25AA%258C%25E5%25AE%25A4%25E6%259D%2590%25E6%2596%2599%2F%25E8%2587%25AA%25E5%25B7%25B1%25E8%25A1%25A5%25E5%2585%2585%2F%25E8%25AE%25BA%25E6%2596%2587%25E5%2586%2599%25E4%25BD%259C%2Fown%2Fbare_conf.pdf。

**Comment by lmk123** [comment]
由于扩展程序的安全性限制，同一个 PDF 文件只能被一个扩展程序处理，所以现在的情况是「Kami」优先处理了 PDF 文档所以就轮不到划词翻译来处理了。
