### ISSUE TITLE
有道API失效

### ISSUE THREAD

**Issue by sudoZhange** [Selection-Translator/crx-selection-translate#301]
需要申请应用？然后填写application id 和 秘钥？没看到应用的秘钥在哪啊

**Comment by lmk123** [comment]
[Wiki](https://github.com/Selection-Translator/crx-selection-translate/wiki/%E7%94%B3%E8%AF%B7%E6%9C%89%E9%81%93%E7%BF%BB%E8%AF%91-API) 里提到过了，有道 API 的接入方式变了，划词翻译暂时还不支持这种新的接入方式。
