### ISSUE TITLE
使用ssX-NG代理pac模式下无法打开词板

### ISSUE THREAD

**Issue by SecondhandRose** [Selection-Translator/crx-selection-translate#309]
使用ssX-NG代理pac模式下无法点开翻译词板
![image](https://user-images.githubusercontent.com/18202375/29547303-d5df00cc-872b-11e7-8834-a6dc9060cf81.png)
切换到全局代理模式就可以打开
![image](https://user-images.githubusercontent.com/18202375/29547188-3121c006-872b-11e7-96dd-35f03f64c5c6.png)
但是在pac模式下的页面划词翻译又可以用。。
![image](https://user-images.githubusercontent.com/18202375/29547235-6e3c5b72-872b-11e7-81f2-e29c0d720ea5.png)
为什么。。

**Comment by lmk123** [comment]
应该是你的 PAC 的问题。

打开 PAC 模式，，然后在浏览器里看看你打不打得开 https://translate.google.com

**Comment by SecondhandRose** [comment]
但是我反复验证，全局模式可以打开，pac模式打不开，不开代理也打不开。。。

**Comment by lmk123** [comment]
今晚我重现一下看看。

**Comment by lmk123** [comment]
#169
