### ISSUE TITLE
部分情况下，划词后会一直卡在「正在查询，请稍候……」，且无法关闭

### ISSUE THREAD

**Issue by nearniu** [Selection-Translator/crx-selection-translate#312]
google浏览器查询没有结果，界面卡住了，小窗口也没有关闭按钮，一直在那！！！
可能与我本地代理有关，此时代理失效导致网络不通畅！
建议根据返回时间判断，超过时间返回服务器忙提示！
![2017-08-31_104617](https://user-images.githubusercontent.com/27255649/29904097-be2f1722-8e39-11e7-88a9-146abe87a349.png)

**Comment by SweetLoli** [comment]
+1，有时候也会出现这种情况，只有刷新页面这个窗口才会消失……

**Comment by lmk123** [comment]
#256

**Comment by sweet-fish** [comment]
最近又出现了，求解决

**Comment by LingChris** [comment]
问题仍然存在，不能自动关闭好歹给个手动关闭入口？
