### ISSUE TITLE
有些单词如果是大写字母的就翻译不了

### ISSUE THREAD

**Issue by DJinXing** [Selection-Translator/crx-selection-translate#313]
比如下面的123图片文件中的单词是翻译不了的，而456图片文件中的就可以。
![456](https://user-images.githubusercontent.com/27340964/30122829-6d8bc6fc-9362-11e7-8d9e-2e68ab867a0f.png)
![123](https://user-images.githubusercontent.com/27340964/30122822-692c4af0-9362-11e7-89c2-cc2f9648099a.png)

**Comment by lmk123** [comment]
结果是谷歌返回给我的，见 https://translate.google.cn/#auto/zh-CN/CAPTCHA

划词翻译可以在翻译的时候将所有大写都转为小写，但是我不确定这样做会不会产生一些副作用……
