### ISSUE TITLE
Mac版QQ浏览器无法进行选项设置

### ISSUE THREAD

**Issue by tenndou** [Selection-Translator/crx-selection-translate#319]
只有logo、划词翻译四个字和右侧的关闭x
下面设置部分js报错了：Uncaught DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

**Comment by lmk123** [comment]
我现在并没有多余的精力去兼容各种套壳浏览器，所以我不会修复非 Chrome 上的任何问题，抱歉。
