### ISSUE TITLE
能提供音标显示吗？

### ISSUE THREAD

**Issue by SoVieTing** [Selection-Translator/crx-selection-translate#321]
使用中发现只有“有道“引擎有音标显示，其他都没有。

看了介绍，谷歌官方没有提供音标。但是百度的能提供下吗？

**Comment by lmk123** [comment]
我正在开发新版的划词翻译，届时会给百度提供音标的

**Comment by jnscode** [comment]
能否增加单独设置音标引擎的功能，没有音标还是很不方便的。

**Comment by oknixus** [comment]
是的！最近发现有道的翻译没有音标了，很困惑

**Comment by oknixus** [comment]
希望可以给Google翻译也加音标，感觉Google翻译，比有道更准确
另外，那个支付宝和微信的二维码不显示了

**Comment by stayfool** [comment]
音标+1

**Comment by lmk123** [comment]
后续同步至 #423
