### ISSUE TITLE
那个，能不能添加“shift+自动选词模式”？

### ISSUE THREAD

**Issue by fukaWestin** [Selection-Translator/crx-selection-translate#325]
就是参考这个插件：
https://chrome.google.com/webstore/detail/%E6%9C%89%E9%81%93%E8%AF%8D%E5%85%B8chrome%E5%88%92%E8%AF%8D%E6%8F%92%E4%BB%B6/eopjamdnofihpioajgfdikhhbobonhbb?utm_source=chrome-ntp-icon

之前一直是使用这个插件的，它是按住ctrl后，自动选中鼠标周围的英文文本进行翻译，对于笔记本用户很友好，毕竟触摸屏划词太麻烦了
不过这个有个缺点就是按ctrl+c复制文本的时候也会触发，应该是快捷键冲突了，希望能改成shift键
总之很谢谢开发者(*^__^*)

**Comment by lmk123** [comment]
这功能已经在开发计划之中了 #88
