### ISSUE TITLE
pdf功能中选中错位

### ISSUE THREAD

**Issue by oyange** [Selection-Translator/crx-selection-translate#329]
1.看论文的时候，选中文本会有轻微的错位，
2.行末连字符无法忽略

**Comment by lmk123** [comment]
能提供出问题的 PDF 文件或网址吗？

**Comment by chen7410** [comment]
![capture](https://user-images.githubusercontent.com/27870739/32086059-884376ec-ba87-11e7-8494-78523f7aa61c.PNG)
这个也是bug。具体情况是双击，就会选取整个句子，但是翻译不出来

**Comment by lmk123** [comment]
选中文本错位是划词翻译内置 PDF 阅读器的问题，新版本中会升级内置的 PDF 阅读器看看能不能修复这个问题；连字符的问题会同步至 #395
