### ISSUE TITLE
6.21 不能进行翻译接口修改，打开选项没有内容

### ISSUE THREAD

**Issue by Likeyong** [Selection-Translator/crx-selection-translate#330]
6.21 不能进行翻译接口修改，打开选项没有内容

**Comment by lmk123** [comment]
检查一下你的 Chorme 版本是否低于 Chrome 40，或者你用的不是 Chorme 而是类似于 QQ、猎豹这一类带有 Chrome 核心的兼容浏览器？

**Comment by lmk123** [comment]
无反馈
