### ISSUE TITLE
ERROR in Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)

### ISSUE THREAD

**Issue by DIYer22** [Selection-Translator/crx-selection-translate#331]
我在`npm run dev` 时候遇到了这个错误
> ERROR in Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)

我是源码编译的node 版本是
> v8.9.1

请问，是不是我版本不对啊？

**Comment by lmk123** [comment]
node-sass 的问题不太清楚，你可以去 https://github.com/sass/node-sass/issues 搜索看看有没有相关的问题和解决方案。

**Comment by lmk123** [comment]
我自己搜索了一下知道是为什么了。

划词翻译依赖的 node-sass 版本是 3.7.0，这个版本的 node-sass 不支持 Linux 64-bit，但是目前最新的 node-sass [v4.6.0](https://github.com/sass/node-sass/releases/tag/v4.6.0) 已经支持了。

所以，升级一下 node-sass 的版本就可以了：

```
npm update node-sass
```

**Comment by DIYer22** [comment]
对现代js还不熟悉 之前搜索了一下 没有头绪才问的 已解决 谢谢啦😄
