### ISSUE TITLE
chromebook上使用划词翻译，有三个问题请教

### ISSUE THREAD

**Issue by nyaang** [Selection-Translator/crx-selection-translate#333]
1."打开翻译盒子时，自动翻译剪切板内的文本"已经被勾选。我在常规网页上复制英文到剪贴板后，没有任何反应。
我用另一台windows 10(1709)、chrome版本 61.0.3163.100的电脑做同样的测试，也没有反应。这个功能现在真的可以正常使用？
2. “file:///”开头协议的本地文件，划词翻译只能是off状态。
我看到这个issue[https://github.com/Selection-Translator/crx-selection-translate/issues/135](url)。里面有说要‘勾选“允许访问文件网址”’，请问这个功能现在是移除了么？
3.“externalfile:drive-”开头的url里，划词翻译只能是off状态。
chromebook中“文件”应用打开google drive里的pdf文件，在chrome地址栏中的地址是“externalfile:drive-”开头的url，划词翻译无法使用。

**Comment by lmk123** [comment]
第一个问题我测试过，在我这是正常的。MacOS 10.12

第二个问题中那个勾选框在扩展程序页（chrome://extensions/）里划词翻译哪一块的下方，不过我不知道 Chromebook 的扩展程序页是否跟 MacOS 上不同。

第三个问题，“externalfile:drive-”开头的 url 应该是被视为 Chrome 内部协议，比如 "chrome://"，这种情况下所有扩展程序都没权限控制。

**Comment by nyaang** [comment]
1.关于第一个问题我又试了一下：
chrome os上，我把chrome的其他扩展都关了只留划词翻译，还是不能自动翻译复制的内容；
windows 10(1709)上做相同的测试，另外把卡巴斯基也关了，结果一样。
2.第二个问题
原来这个设置在这里，不好意思我以为这个功能在划词翻译的设置界面里所以没看到。chromebook的扩展程序页是一样的。
3.第三个问题
明白了，谢谢。我把google drive里的pdf下载到本地，以“file:///”开头打开后可以正常使用划词翻译了。

**Comment by lmk123** [comment]
我想第一个问题是划词翻译没有描述清楚。

划词翻译里的「打开翻译盒子时，自动翻译剪切板内的文本」是指*点开地址栏右边的划词翻译图标后（即“翻译盒子”），划词翻译会自动将剪切板内的文本粘贴进翻译框中并翻译*，而**不是**指「一旦你复制了一段文本，划词翻译就会自动翻译」

**Comment by nyaang** [comment]
原来是这个意思。我能正常使用这个功能。谢谢。

**Comment by Xyyyyyyyyyyyyyy** [comment]
谢谢，我也找到了
