### ISSUE TITLE
重启浏览器插件损坏

### ISSUE THREAD

**Issue by bigding** [Selection-Translator/crx-selection-translate#338]
我的chrome浏览器现在每次重启之后沙拉划词翻译这个插件就会显示可能以损坏,.如图所示
![salad](https://user-images.githubusercontent.com/18662372/33937264-bf55b092-e03d-11e7-9f9d-72fd18bf3350.png)

我电脑的情况为windows10,chrome版本:62.0.3202.94 (正式版本) （32 位） (cohort: Stable) 
chrome安装的插件有Adblock Plus,Proxy SwitchyOmega.这两个插件运行良好,重启也不会损坏.

我尝试过在github上面下载crx文件安装和在谷歌应用商店安装,在当时安装完成后都能够使用,但是一旦重启就会显示插件已损坏.同事的电脑也是安装的这款插件,不存在此问题.

**Comment by lmk123** [comment]
抱歉，我没有解决这个问题的经验，你可以尝试一下安装一个 Chrome 64 位的试试。

**Comment by bigding** [comment]
好的  感谢
