### ISSUE TITLE
开发者大大可以适配Microsoft Edge吗？

### ISSUE THREAD

**Issue by frendguo** [Selection-Translator/crx-selection-translate#339]
微软的那款翻译实在是不好用，一直用的这款。开发者大大可以适配下吗？

**Comment by lmk123** [comment]
要求我适配 Firefox 的有很多，但要求我适配 Edge 的还是第一次……

**Comment by Frendguo** [comment]
😁😁😁   看了下文档，看起来好像很简单的样子 https://docs.microsoft.com/zh-cn/microsoft-edge/extensions/guides/porting-chrome-extensions   大大可以抽空看看~

**Comment by lynnhere** [comment]
划词翻译太给力，已经安利身边不少人在用了，同求适配 Microsoft Edge，平时外出不带电源情况下 Edge 浏览器用得多一些，但微软自己的翻译插件太垃圾了，商店里也确实没有其他的翻译扩展，所以希望开发者大大能适配一下。

**Comment by CyrusF** [comment]
新版 Edge 已经几乎兼容 Chrome 插件，我基于 v6.4.9 版本简单做了一下适配，可以在 [这里](https://github.com/CyrusF/crx-selection-translate/releases/tag/v6.4.9-new-edge) 下载。我也已经给 Microsoft Store 提交了 Add on，正在审核。

**Comment by lmk123** [comment]
我已经开始在适配了，大概明天完成

**Comment by lmk123** [comment]
划词翻译已在 Microsofe Store 中提交审核

**Comment by CyrusF** [comment]
> 我已经开始在适配了，大概明天完成， @CyrusF 你把你的提交撤回吧，我提交之后就把安装链接更新在这里

好的，那我撤回一下

**Comment by lmk123** [comment]
划词翻译已上架 Edge 商店 https://microsoftedge.microsoft.com/addons/detail/oikmahiipjniocckomdccmplodldodja
