### ISSUE TITLE
单词被换行的时候翻译有问题

### ISSUE THREAD

**Issue by zxf8665905** [Selection-Translator/crx-selection-translate#340]
在阅读pdf论文的时候，换行单词翻译会有问题。比如下图的：permutation （排列） 这个单词，会被翻译成突变（mutation）
![image](https://user-images.githubusercontent.com/9147295/34139029-73569f20-e4ad-11e7-8c9f-1bcc499922a9.png)

pdf链接：https://arxiv.org/pdf/1712.00617

**Comment by lmk123** [comment]
这其实是因为有了连字符，跟换行没有关系，你直接翻译 `per-mutation` 也是有问题的……

我考虑一下我能不能优化一下这种场景吧

**Comment by lmk123** [comment]
后续会同步至 #395
