### ISSUE TITLE
划词翻译的时候，能不能增加音标等信息？

### ISSUE THREAD

**Issue by mrdulin** [Selection-Translator/crx-selection-translate#342]
划词翻译的信息很少，希望能增加音标等信息。
![image](https://user-images.githubusercontent.com/17866683/34331087-839d4dd8-e95e-11e7-950e-7636f1a79df3.png)

或者可以让用户自行设置显示音标等信息。

**Comment by biuuu** [comment]
这个功能有必要，办公室的电脑听不了声音

**Comment by lautumn1990** [comment]
希望增加一个单词翻译的时候显示音标功能

**Comment by lmk123** [comment]
#321

**Comment by tongchuan** [comment]
能否加音标，没有音标好麻烦

**Comment by perock** [comment]
强烈建议，增加音标！

**Comment by zzxcvbnm19** [comment]
强烈建议，增加音标！
