### ISSUE TITLE
谷歌翻译 自动选择 目标语言 翻译内容还是原文

### ISSUE THREAD

**Issue by zerolinke** [Selection-Translator/crx-selection-translate#344]
卸载重装反复试了下
百度翻译-自动是正常的
切换
谷歌翻译-原文输出-手动把目标语言选成中文才行-但是换一个单词又是自动选择-原文输出

**Comment by lmk123** [comment]
在我这里是正常的。

![image](https://user-images.githubusercontent.com/5035625/34399213-333beb06-ebc0-11e7-86d2-536d47d057ad.png)

能否提供一下你的划词翻译版本号和出现问题的截图给我？

**Comment by cololi** [comment]
Version 6.3.1 Chrome 63.0.3239.108 系统语言英文 
![image](https://user-images.githubusercontent.com/10243794/34399518-febb8c26-ebc2-11e7-8b1b-126deeff21c2.png)

![image](https://user-images.githubusercontent.com/10243794/34399507-e245a914-ebc2-11e7-8e15-311effb93892.png)

**Comment by lmk123** [comment]
感谢反馈，我会在下一个版本中改进。

**Comment by zerolinke** [comment]
我试了下 ,你发的图用的是谷歌翻译(国内),我如果选了国内也可以,不行的是谷歌翻译[没有国内的那个选项]

**Comment by lmk123** [comment]
![image](https://user-images.githubusercontent.com/5035625/34402615-af6c5d92-ebdd-11e7-8581-ffc053332185.png)

我用不带国内的谷歌翻译也是正常的。你是不是跟 @cololi 的情况一样，将系统或者浏览器的默认语言改为了英语？

**Comment by zerolinke** [comment]
嗯 可以之前一只是好的

**Comment by lmk123** [comment]
v6.3.1 重写了一下内置的翻译接口，应该是漏掉了一个逻辑，下个版本会修复。

**Comment by chiseller** [comment]
最近也发现了这个问题

**Comment by Ryanhui** [comment]
是否跟系统语言有关？我的环境是英文的OS X ，翻译结果依然是英文，需要手动选择目标语言。

**Comment by lmk123** [comment]
@Ryanhui 确实跟系统语言有关

**Comment by JonoloLuo** [comment]
我的也是这个问题呀 请问怎么可以临时解决呀

**Comment by lmk123** [comment]
@JonoloLuo 把浏览器的语言改为简体中文试试

**Comment by lmk123** [comment]
刚才我发布了 v6.3.3 解决了这个问题，大家可以在扩展程序页手动更新到最新版。

**Comment by chile-zhong** [comment]
问题还是存在 6.3.3版本
