### ISSUE TITLE
有道翻译不显示单词释义

### ISSUE THREAD

**Issue by Jl-wei** [Selection-Translator/crx-selection-translate#346]
之前使用有道翻译来翻译单个单词时，会显示单词的详细解释，包含多个中文含义，还有单词的音标等等。现在只显示一个中文解释。

**Comment by lmk123** [comment]
是会有这样的情况，因为原本包含音标、中文解释的有道翻译接口现在要收费了，我改为直接使用有道网页翻译的结果，但有道网页翻译是不包含这些的，例如 http://fanyi.youdao.com/translate?i=test

目前你可以使用百度翻译，现在百度翻译也会有音标和详细解释了。后面我会对有道做优化，从有道的单词解释网页中抓取音标等数据。

**Comment by greatghoul** [comment]
https://github.com/GDG-Xian/crx-transit/blob/master/src/js/translators/youdao_translator.js
https://github.com/greatghoul/smooth-translator/blob/master/app/scripts/translators/youdao-web-translator.js

http://mobile.youdao.com/dict?le=eng&q=good

使用 mobile  web 页面，你可以参考一下。

**Comment by caigaopei** [comment]
@lmk123 目前百度翻译用不了, @greatghoul 给的mobile页面抓取翻译音标信息可行的. 大佬有考虑过?

**Comment by greatghoul** [comment]
我本来是考虑使用百度的收费 API 的，不过发现它只有翻译接口，没有词典的接口。

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，现在有道和百度都会有单词释义了。必应翻译不再支持，你们可以手动更新后试一下，有问题欢迎反馈！
