### ISSUE TITLE
还有目标翻译语言的问题

### ISSUE THREAD

**Issue by CharlieWalker** [Selection-Translator/crx-selection-translate#348]
系统是英文的，普通也是装的英文软件，所以基本上软件都会以为自己是装在一个英文环境的电脑上。但是偶尔有需要查字典的单词。之前是好的，大概1-2星期之前，发现google翻译会自动翻译成系统语言，也就是英语。于是翻译变得没有意义了，希望改进。

**Comment by zoglun** [comment]
同样问题

**Comment by lmk123** [comment]
#344 重复
