### ISSUE TITLE
插件导致mac 上看pdf 不流畅

### ISSUE THREAD

**Issue by zxf8665905** [Selection-Translator/crx-selection-translate#349]
用了这个插件后，mac 上看pdf 不流畅，特别是双指缩放的时候。

**Comment by lmk123** [comment]
你是不是开启了 PDF 翻译功能？如果是，划词翻译会将 PDF 使用划词翻译内置的 PDF 阅读器打开，所以可能会没有 Chrome 自带的 PDF 阅读器流畅。

你可以关闭 PDF 翻译功能使用 Chrome 内置阅读器。
