### ISSUE TITLE
谷歌翻译无法作为默认翻译

### ISSUE THREAD

**Issue by rabiachan** [Selection-Translator/crx-selection-translate#350]
想知道如何把谷歌翻译作为默认翻译，每次划词都默认百度翻译，需要反复手动选择谷歌翻译，实在太麻烦了，有没有设置默认翻译的设置？

**Comment by lmk123** [comment]
设置里面是可以改的，但是刚才我发现划词翻译的设置页打不开了，我更新了 6.3.2 版本解决了这个问题，你可以稍候试试能不能打开，感谢反馈！
