### ISSUE TITLE
有些网站启用不了

### ISSUE THREAD

**Issue by Gxuebin** [Selection-Translator/crx-selection-translate#351]
![tim 20180102115506](https://user-images.githubusercontent.com/20697809/34473958-dfd634e2-efb3-11e7-92e7-fe4af5fce5a6.png)

**Comment by lmk123** [comment]
我这边无法重现，但这可能是因为目前判断是否有权限的方式有问题，我会在新版本中优化这个判断方法。你可以尝试一下关闭当前网页后重新打开，或者重装划词翻译。

![image](https://user-images.githubusercontent.com/5035625/34474161-086b1740-efb6-11e7-8bb9-3ab77e7dbb5d.png)

**Comment by Gxuebin** [comment]
好了 谢谢

发自我的 iPhone
