### ISSUE TITLE
有道翻译和官网的结果不一样

### ISSUE THREAD

**Issue by zxf8665905** [Selection-Translator/crx-selection-translate#353]
有道翻译和官网的结果不一样，而且感觉官网的翻译结果要更好一些，是不是用了老的API了？
---
![image](https://user-images.githubusercontent.com/9147295/34484919-d7da5d78-f002-11e7-8fc5-301ead765a28.png)
---
![image](https://user-images.githubusercontent.com/9147295/34484933-e60950e8-f002-11e7-94c2-850b1510e5f9.png)

**Comment by lmk123** [comment]
接口上忘带了两个参数 😂 

![image](https://user-images.githubusercontent.com/5035625/34496780-d5bb272e-f035-11e7-843c-d08b17987a54.png)

**Comment by lmk123** [comment]
目前这两个参数已经带上去了，翻译结果应该是一致的了。
