### ISSUE TITLE
谷歌翻译（国内）在在使用翻墙软件时和不使用的翻译完全不一样

### ISSUE THREAD

**Issue by JUNER925** [Selection-Translator/crx-selection-translate#354]
谷歌翻译（国内）在在使用翻墙软件时和不使用的翻译完全不一样，不使用vpn就是机翻。

**Comment by rickertanks** [comment]
推荐一个自用的shadowsocks  SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/

**Comment by lmk123** [comment]
举个例子？

**Comment by VDerGoW** [comment]
用了VPN难道是人翻？😂  我没遇到这个问题。
