### ISSUE TITLE
划词翻译不能用了

### ISSUE THREAD

**Issue by RegulusyLei** [Selection-Translator/crx-selection-translate#357]
"正在查询, 请稍后..."之后就是一片空白, 不能用了吗?

**Comment by lmk123** [comment]
![image](https://user-images.githubusercontent.com/5035625/34496591-080875fc-f035-11e7-962c-3934c2d583f8.png)

提供一下不能用的截图？

**Comment by hugo2lee** [comment]
我的也是

**Comment by hugo2lee** [comment]
![image](https://user-images.githubusercontent.com/22361521/34546465-f777c3d2-f12e-11e7-9bbe-3f1481e9b58b.png)

**Comment by AmazingXiaomi** [comment]
me too

**Comment by AmazingXiaomi** [comment]
![image](https://user-images.githubusercontent.com/30220803/34551146-ced3f784-f151-11e7-911a-33780327b417.png)

**Comment by lmk123** [comment]
#347
