### ISSUE TITLE
谷歌翻译（非国内）问题

### ISSUE THREAD

**Issue by reaCodes** [Selection-Translator/crx-selection-translate#358]
我之前反映过一个问题，#251

6.3.3这个新版本依然没有解决这个问题，可能作者精力有限，计划把这个问题放在了下个版本解决，辛苦了。
带来的麻烦是，谷歌翻译（非国内版）每次翻译英文，默认英到英，显然没有翻译的作用，只能手动调节目标语言为中文，关键这个设置还不能保存，页面一关设置就没了

之前用有道，发现句段翻译有道还是远远不如谷歌，加上最近谷歌翻译加入了人工智能算法，提升很大，
我用的翻墙软件，使用谷歌翻译（国内）反应慢，所以想用谷歌翻译。

麻烦你告诉我如何解决，感谢！@lmk123

**Comment by lmk123** [comment]
目前这个问题应该已经解决了才对，你升级到 v6.3.3 试试。

附上我这边的截图：

![image](https://user-images.githubusercontent.com/5035625/34512269-2d1367b4-f09c-11e7-9fba-d4cf4ed068ad.png)

**Comment by reaCodes** [comment]
![image](https://user-images.githubusercontent.com/13817254/34512343-d2daba44-f09c-11e7-9a54-4e497af585ac.png)

我这里看还没有，我不知道问题出在哪里，我以为是请求的ip地址问题，换了几个不同国家的，返回的一样的结果

**Comment by reaCodes** [comment]
![image](https://user-images.githubusercontent.com/13817254/34512512-f59681a2-f09d-11e7-969d-8e07b88d1633.png)
--------------------------------
另外，国内的谷歌翻译功能是正常的

**Comment by shruru** [comment]
很棒的插件，先感谢下作者。这是我在Github的第一个留言。
我这里也是一样，6.3.3 最新版本。
谷歌翻译无法保存我的设定，每次都是 自动选择 -- 然后就是 英文还是英文。

Mac OSX ，Chrome 63.0.3239.132
之前几个版本一直好好的。没问题。

**Comment by reaCodes** [comment]
感谢反馈！@shruru
不知道为什么作者那边就没有这个问题，只能暂时用国内谷歌翻译了😊

**Comment by 74sharlock** [comment]
同样的设置，同样的版本（6.3.3），同样的问题（无法自动识别）

环境：OSX 10.12.4，chrome 63.0.3239.84。

**Comment by zqwzshm** [comment]
同样的问题 (version 6.3.3)
环境:
  Chrome 62.0.3202.89 
  Fedora 26
我猜是作者尝试重现的时候没用国外的 ip？我的出网ip是美国的，可能谷歌那边会识别ip的位置？

**Comment by reaCodes** [comment]
@zqwzshm 我试了使用新加坡，香港，菲律宾的全局代理，得到一样的结果，感觉跟ip关系不大吧

**Comment by chiseller** [comment]
先感谢下作者，版本6.3.3经过测试谷歌翻译（国内）可以翻译为中文，谷歌翻译（国外）还是原文不会改变。Chrome63.0，系统Mac os 10.12.13

**Comment by zqwzshm** [comment]
换了个环境，能正常用谷歌翻译了，不太确定是什么原因
环境：
Version 6.3.3
Chrome 63.0.3239.132
Windows 7
走的应该是ipv6流量，国内地址

**Comment by chermy** [comment]
我正准备反馈这个问题 发现大家都碰到了. 我也一样, 在设置里改成 国内版就正常了. 
![default](https://user-images.githubusercontent.com/5954008/34930242-9600b55e-fa03-11e7-9122-b30f08afebf3.png)
![default](https://user-images.githubusercontent.com/5954008/34930243-96328584-fa03-11e7-8e8c-c39a8956d703.png)

**Comment by reaCodes** [comment]
我刚才发现国内的谷歌翻译和国外的谷歌翻译结果，并不是完全一样的，差距在于英文朗读，明显国外的谷歌翻译朗读更加自然，国内的太生硬。

**Comment by reaCodes** [comment]
这个问题在v6.4.0版本中，已经得到解决

**Comment by lmk123** [comment]
🎉

**Comment by shruru** [comment]
太好了。终于解决了。虽然好像几周前已经 ok 了。
