### ISSUE TITLE
建议：增加仅右键才翻译

### ISSUE THREAD

**Issue by vikyd** [Selection-Translator/crx-selection-translate#360]
希望可以：
- `划词` 后不显示 `翻译图标`，且不显示 `翻译内容`
- `右键` 后才显示 `翻译项`

原因：
- 我使用翻译的频率不高，希望划词后不显示任何东西（不显示`翻译按钮`，且不显示`翻译结果`）

**Comment by lmk123** [comment]
右键菜单里已经有翻译选项了。

**Comment by vikyd** [comment]
@lmk123 ，我只想配置为：保留右键菜单翻译选项，`且`划词后不显示任何内容（觉得有干扰，因为使用频率不高）

**Comment by lmk123** [comment]
勾选「在所有网站中禁用划词翻译」即可

**Comment by vikyd** [comment]
原来在这里设置，OK了， thx
