### ISSUE TITLE
麻烦作者进来看下，对「划词翻译」有帮助的东西

### ISSUE THREAD

**Issue by hongquan66** [Selection-Translator/crx-selection-translate#362]
首先感谢作者提供这个插件帮助我们这帮不努力学习的人阅读外语文章
今天使用时发现百度翻译不能用了，不知道是不是因为近期百度翻译接口改版的问题
我对百度的翻译接口也一直有关注，可以参看一下我的博客 [https://www.devtool.top/article/42](https://www.devtool.top/article/42)
目前我自己使用没有发现其他限制，如果你在使用过程中发现什么问题可以告诉我，交流交流
希望「划词翻译」百度接口早日康复 ~

**Comment by lmk123** [comment]
百度翻译的接口我看过了，只是我最近没有时间把它整合到划词翻译里去。

也许你可以提个 PR？

**Comment by hongquan66** [comment]
OK 我抽空读下源码

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你可以手动更新后试一下，有问题欢迎反馈！
