### ISSUE TITLE
本人在日本，使用划词时会自动翻译为日文，每次都得自己再点一次，希望作者大大能关注。

### ISSUE THREAD

**Issue by abca12a** [Selection-Translator/crx-selection-translate#365]
可能是我设置上的问题，如果是设置上的问题请告诉我怎么设置，谢谢

**Comment by lmk123** [comment]
不是你设置上的问题 😂 这实际上是一个 bug

**Comment by abca12a** [comment]
谢谢

**Comment by lmk123** [comment]
#358

**Comment by lulu002** [comment]
解决办法是，在设置中选择为，google国内。如图所示。
![image](https://user-images.githubusercontent.com/523857/36628850-27400232-1989-11e8-9889-e2f41fda1cd7.png)
