### ISSUE TITLE
感谢提供了这么多年的优秀服务，但是现在这个工具越来越差了，希望有朝一日能够恢复往日的优秀

### ISSUE THREAD

**Issue by oknixus** [Selection-Translator/crx-selection-translate#366]
去查了一下有道翻译API的收费标准，http://ai.youdao.com/docs/doc-trans-price.s#p03
希望作者可以出一个收费的版本，API费用 + 自己的辛勤付出 = 收费版本的费用

我相信，有非常多的用户，会为优秀的服务支付相应的费用！
一定有无数用户，宁愿支付合理的费用，享受优质的服务，也不愿意在免费蹩脚的服务上，浪费自己的时间！

**Comment by reaCodes** [comment]
我也支持可以考虑收费服务，好的服务一般都不会免费😂

**Comment by oknixus** [comment]
@reaCodes 快点吧！现在的用起来，真难受！Google的翻译，还要选目标语言！
快点恢复往日的光辉吧！

**Comment by lmk123** [comment]
事实上我已经有一个开发收费版本的计划了，所以目前的版本基本上是处于“荒废”状态，但是改造成收费版本的时间成本很高，要考虑和完善的事情很多，所以尽情期待吧 😂
