### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by certsblock** [Selection-Translator/crx-selection-translate#372]
可不可以增加一项功能，将查询过的保存下来，保存方式可分为两种，1.单词2.单词+释义； 保存成.txt格式就好。方便学习新单词

**Comment by simonChen0317** [comment]
怎么没有修改默认翻译工具的选项。我想默认使用谷歌翻译怎么弄？

**Comment by lmk123** [comment]
生词本功能正在考虑中 #464
