### ISSUE TITLE
强切请求恢复英文单词音标注释

### ISSUE THREAD

**Issue by duboya** [Selection-Translator/crx-selection-translate#373]
首先作为该插件的受益人，很感谢提供的服务！
同时作为一名老用户，很想提一个建议：恢复之前百度的单词音标注释！这是我选择该插件最重要原因之一，相信也有不少用户跟我一样。
请加以考虑！谢谢！！

**Comment by lmk123** [comment]
你说的是有道不是百度吧？百度翻译暂时不能用了，有道翻译没有注释的原因见 #346
