### ISSUE TITLE
在 Material Design 扩展程序页面下设置页面无法向下滚动

### ISSUE THREAD

**Issue by mxalbert1996** [Selection-Translator/crx-selection-translate#374]
我用的 Chrome Dev 66 默认使用 Material Design 版扩展程序页面（其实从不久之前就开始了，更早的版本可以把 <chrome://flags/#enable-md-extensions> 设置为 Enabled 来启用），在此页面上点击划词翻译的扩展程序选项时弹出的页面无法滚动（没有滚动条也无法通过鼠标或键盘滚动）。

**Comment by lmk123** [comment]
非 Stable 版的问题不会考虑修复，因为无法确认是 Chrome 造成的还是划词翻译造成的。
