### ISSUE TITLE
不妙，国内谷歌翻译地址被墙啦？

### ISSUE THREAD

**Issue by reaCodes** [Selection-Translator/crx-selection-translate#375]
国内版使用出现了问题，使用代理一切正常，貌似网址被墙了。
国际版谷歌翻译又不能用，作者怎么看？

**Comment by lmk123** [comment]
我这边使用国内谷歌翻译一切正常，用 Ping 工具测试了一下，国内谷歌翻译似乎并没有被墙：http://ping.chinaz.com/translate.google.cn

**Comment by CHN-STUDENT** [comment]
@lmk123 貌似现在已经GG，现在不F*能用的只有有道了，希望您赶快修复其他翻译源。

**Comment by h2so** [comment]
国内谷歌翻译一直没有被墙过吧，用了很多年，一直是正常的

**Comment by CHN-STUDENT** [comment]
@h2so 这几天我用的有点抽风，然后我修改host之后好得多。

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你们可以手动更新后试一下，有问题欢迎反馈！

谷歌翻译不能用的话我这边也无能为力，毕竟扩展程序没有权限帮你们修改 hosts 😂
