### ISSUE TITLE
这两天使用百度或有道翻译会返回接口错误的数据

### ISSUE THREAD

**Issue by yyy123zc** [Selection-Translator/crx-selection-translate#377]
提示如下：
接口返回了错误的数据，请稍候重试。有道翻译接口出错了 重试

**Comment by lmk123** [comment]
百度确实失效了，这是一个已知问题，但是我这边使用有道是正常的，你这边仍然无法用有道吗？顺便提一下，你需要升级到最新版才能正常使用有道，有道把旧接口停用了，只有最新版划词翻译才用的是新接口。

**Comment by yyy123zc** [comment]
首先谢谢回复。
当前版本：v6.3.3， 已是最新版本。
百度一直不能。
有道有时能翻译有时不能，可能与时间有关系，半夜总是能翻译，白天偶尔能翻译。不知原因。但windows下的有道翻译PC所有时间都能翻译。

________________________________
dzqn-yb@hotmail.com

发件人： mingkaili<mailto:notifications@github.com>
发送时间： 2018-02-24 14:40
收件人： Selection-Translator/crx-selection-translate<mailto:crx-selection-translate@noreply.github.com>
抄送： 独醉千年<mailto:dzqnyb@gmail.com>; Author<mailto:author@noreply.github.com>
主题： Re: [Selection-Translator/crx-selection-translate] 这两天使用百度或有道翻译会返回接口错误的数据 (#377)

百度确实失效了，这是一个已知问题，但是我这边使用有道是正常的，你这边仍然无法用有道吗？顺便提一下，你需要升级到最新版才能正常使用有道，有道把旧接口停用了，只有最新版划词翻译才用的是新接口。

**Comment by byxn** [comment]
我的也是，除了google都失效了

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你们可以手动更新后试一下，有问题欢迎反馈！
