### ISSUE TITLE
很优秀的插件，强烈建议作者有空的时候优化一下界面。

### ISSUE THREAD

**Issue by xtualong** [Selection-Translator/crx-selection-translate#379]
功能上很强大，也很简单易用，就是界面有点……尴尬……那两条宽宽的原谅绿实在是太刺眼了，希望作者有空可以优化下，最好能弄成半透明或者清晰淡雅点的风格，能有几个皮肤可选就更好了。
另外右下角的“via 有道翻译”要是能去掉应该会显得界面更简介一些。
感谢作者

**Comment by theratlesnake** [comment]
我倒觉得现在界面很好，简洁简单，而且右下角还能提示用的哪个接口，非常完美，来个火狐版就更好了。

**Comment by lmk123** [comment]
新版本会优化界面的
