### ISSUE TITLE
linux 上打开本地 PDF 时没有用划词翻译的 PDF 阅读器，而是用的 Chrome 的阅读器

### ISSUE THREAD

**Issue by SLZhang-CUG** [Selection-Translator/crx-selection-translate#381]
我这里只有在打开PDF连接的时候使用划词翻译打开的，如果是本地的，右击打开pdf文件会用chrome默认的pdf阅读器。系统是deepin linux 15.5，chrome 63.0.3239.132（正式版本） （64 位）

**Comment by lmk123** [comment]
macOS 上对 PDF 文件使用 Chrome 打开用的就是划词翻译的 PDF 阅读器，我找个时间装个虚拟机看看为什么 linux 上不行

**Comment by lmk123** [comment]
我突然想到，是不是你没有在扩展设置里勾选「允许访问本地文件网址」？

**Comment by SLZhang-CUG** [comment]
非常感谢，果真是

mingkaili <notifications@github.com> 于2018年11月9日周五 上午11:32写道：
