### ISSUE TITLE
现在默认的目的语种是自动选择而不是之前的中文简体

### ISSUE THREAD

**Issue by LHertz** [Selection-Translator/crx-selection-translate#382]
使用划词翻译很久了，非常感谢作者无私付出~
最近使用过程中出现一个问题：之前取词之后会自动翻译为中文简体，但是最近在目的语种那里默认为“自动选择”，结果就是把英文原文显示了一遍，需要手动到悬浮框的设置里面改为中文简体，但是打开一个新的页面之后，又会变成默认的自动选择。。。。
是我哪里的设置出现了问题吗？

**Comment by lmk123** [comment]
不是你的问题，这其实是划词翻译的 bug 😂 见 #358
