### ISSUE TITLE
如何设置默认翻译引擎

### ISSUE THREAD

**Issue by S1xe** [Selection-Translator/crx-selection-translate#383]
版本:V6.3.3
当前默认翻译引擎为百度翻译，请问如何能够设置其他翻译引擎作为默认引擎？

**Comment by lmk123** [comment]
在设置页。

**Comment by S1xe** [comment]
![image](https://user-images.githubusercontent.com/17163641/37238749-ff1161ae-2467-11e8-940f-0afca8c44b99.png)
但是我在设置页并没有看到相关设置默认引擎

**Comment by lmk123** [comment]
你有往下滚动吗？

![image](https://user-images.githubusercontent.com/5035625/37263481-6651b0e0-25e3-11e8-9b61-184a26596ce7.png)

**Comment by S1xe** [comment]
。。。这原始界面不能滚动，之前尝试过。

**Comment by S1xe** [comment]
缩放倒是可以看到下面的选项

**Comment by S1xe** [comment]
暂时怀疑可能是其他冲突，问题解决了，tks

**Comment by S1xe** [comment]
我这里也录屏演示了下 我当前chrome是无法正常滚动该选项卡 作为参考吧
![problem](https://user-images.githubusercontent.com/17163641/37263823-e2b8e72e-25e4-11e8-85a9-91ff18f78a31.gif)

**Comment by lmk123** [comment]
看来可能有这个问题，能提供一下你的 Chrome 版本号和操作系统吗？

**Comment by lmk123** [comment]
原来已经有人提出一样的问题了，这个问题我关闭，后续在另一个问题 #387 跟进

**Comment by S1xe** [comment]
OS：Win10 专业版
Chrome：版本 66.0.3343.4（正式版本） （64 位）
