### ISSUE TITLE
搜索无结果时一直停留在“正在查询，请稍后...”界面

### ISSUE THREAD

**Issue by nearniu** [Selection-Translator/crx-selection-translate#384]
![image](https://user-images.githubusercontent.com/27255649/37084034-566646ba-222c-11e8-82c7-ac7da549bd37.png)
详细信息：设置有道接口，大部分能搜索到结果，少部分无法搜索到结果，搜索不到时，一直停留在如图“正在查询，请稍后...”界面，无关闭按钮无法关闭该小窗口，也无法点击其它选项更改翻译接口，只有刷新页面才能去除该小窗口。建议增加——长时间无结果时结束查询，提示重试，而不是一直等待查询结果。

**Comment by nearniu** [comment]
又出现了，网络正常，但一直提示正在查询请稍后......点击小窗口的右上角小箭头也没反应！

**Comment by lmk123** [comment]
这是一个 bug #515

**Comment by Pnalson** [comment]
版本6.4.5 还有这个bug，卡死，无法退出
![image](https://user-images.githubusercontent.com/18171453/59523192-42ce4900-8f03-11e9-90e7-97c96bf0869e.png)
