### ISSUE TITLE
设置页面无法滚动

### ISSUE THREAD

**Issue by ziyouwuji** [Selection-Translator/crx-selection-translate#387]
Google Chrome | 66.0.3346.9 (正式版本) （32 位）
设置页面无法滚动，无法展现所有设置项

**Comment by J-fla** [comment]
我也有这个问题，（Chrome 65.0.3325.146）
从翻译筛选开始后面都看不到！

**Comment by lmk123** [comment]
正在排查中，目前可以通过缩放设置页的方式看到后面的设置，见 https://github.com/Selection-Translator/crx-selection-translate/issues/383#issuecomment-372181502

**Comment by LeoSpark** [comment]
这个应该是版本兼容问题：
https://developer.chrome.com/extensions/optionsV2#migration

**Comment by lmk123** [comment]
v6.3.4 已经修复这个问题了，升级之后再试试
