### ISSUE TITLE
嗯，这个插件还能再烂点吗？一直走下坡路

### ISSUE THREAD

**Issue by oknixus** [Selection-Translator/crx-selection-translate#394]

**Comment by lmk123** [comment]
不如你来负责维护？

**Comment by oknixus** [comment]
虽然说的是事实，但是态度太恶劣了，抱歉！

**Comment by lmk123** [comment]
你说的是事实没错，但换作是你，你可以保证自己会坚持维护一个免费的开源项目四年时间吗？

你要是真不忍心看它越来越烂，代码就在这里，你完全可以自己动手、或者花钱找一个会写代码的人帮你完善它，光凭嘴上说说它就能越来越好了？

**Comment by oknixus** [comment]
是的是的，我承认自己的错误！
对不起！您辛苦了！
希望您出个VIP版本，或者留个接口，让用户自己去购买付费的API，谢谢！
我搜一下，全世界只有您的这个扩展是最棒的，只是没有之前好用了！
谢谢！
