### ISSUE TITLE
希望修复其他的国内翻译源

### ISSUE THREAD

**Issue by CHN-STUDENT** [Selection-Translator/crx-selection-translate#398]
这几天突然发现某歌失效了，面前划词翻译唯一能用的国内就是有道了，希望作者能尽快修复其他的国内翻译源，谢谢！！！

https://github.com/Selection-Translator/crx-selection-translate/issues/375

刚试了下用`Hosts`文件还能用
 `translate.google.cn 203.208.41.87`

**Comment by CHN-STUDENT** [comment]
另外有道翻译发现只能翻译一句话？请教是我的使用方法不对吗

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你可以手动更新后试一下，有问题欢迎反馈！

谷歌翻译的问题我这边其实是无能为力的，毕竟我没法帮你去修改 hosts 😂
