### ISSUE TITLE
这几天更新的版本一点“译”就卡死啊

### ISSUE THREAD

**Issue by gggccc44** [Selection-Translator/crx-selection-translate#400]
而且影响几个同域名的网页，做个不更新的长期版放这里手工装算了

还有我发现设置有时候打不开貌似是因为那个谷歌统计的脚本不能访问造成的

**Comment by gggccc44** [comment]
经测试不是完全卡死，等很久会出现结果

**Comment by gggccc44** [comment]
经过关闭扩展测试，有可能跟tampermonkey本身或者运行的脚本有关，禁止了脚本就没问题，看来得慢慢找下是哪个的毛病，奇怪的是这次更新到6.3以后才出现的

**Comment by gggccc44** [comment]
貌似找到原因了，貌似网页限制解除脚本造成的，禁止了那个脚本就正常了，但是以前都没有啊

脚本地址
https://greasyfork.org/zh-CN/scripts/14146
开发
https://github.com/Cat7373/remove-web-limits

准备去反馈看看，不过那脚本都2016的了，或者划词翻译自己看看怎么搞？

**Comment by lmk123** [comment]
赞！也有其他用户反馈划词翻译会卡死，但我这边没法重现。

另外我不打算针对这个脚本去改划词翻译的代码，如果每次有其他脚本影响到划词翻译都需要我一个个去适配的话那就没完没了了。
