### ISSUE TITLE
效果图里有音标展示，怎么安装完了没有音标只有朗读呢？

### ISSUE THREAD

**Issue by laterz** [Selection-Translator/crx-selection-translate#401]
插件version:6.3.4
chrome version:64.0.3282.119
如果是有人建议取消的，那我建议留个设置选项，因为有人就需要看下音标

**Comment by lmk123** [comment]
因为效果图上用的是有道翻译，三年前的有道翻译是有音标的，但三年后的现在它没音标了。

我正在开发新版划词翻译，到时候就会有音标了。
