### ISSUE TITLE
浮窗的位置大小问题

### ISSUE THREAD

**Issue by GH01** [Selection-Translator/crx-selection-translate#403]
我目前的用法：
选中文字，按下快捷键，浮窗出现在(0,0)处。

遇到的问题：
当文字篇幅大时，浮窗的底边贴底，但浮窗顶部却因抬升而不可见。

建议：
1. 浮窗应被限于可见区域内，必要时应有纵滚条。
2. 当浮窗贴右（或贴底）时，不应被网页的纵滚条（或横滚条）遮挡。

**Comment by lmk123** [comment]
这其实是一个 bug #458
