### ISSUE TITLE
划词翻译报错

### ISSUE THREAD

**Issue by LiWenChen** [Selection-Translator/crx-selection-translate#404]
连接到翻译引擎时发生了错误，请刷新网页或重启浏览器后再试。 重试。手动选择谷歌没有报错其他都报错

**Comment by lmk123** [comment]
出现这个问题一般是因为划词翻译自动更新后，浏览器没有重启导致的，重启一下浏览器就可以了。

如果你试过之后还是有问题，欢迎反馈！
