### ISSUE TITLE
显示 正在查询 请稍候... 然后就卡在那了

### ISSUE THREAD

**Issue by Webwwl** [Selection-Translator/crx-selection-translate#406]
我在翻译一些词 如 Node.js 时，显示 正在查询 请稍候... 然后就卡在那了，窗口关不掉 只能关闭网页

**Comment by lmk123** [comment]
macOS Chrome 66 无法重现，能提供更多重现条件吗？

**Comment by rsinensis** [comment]
我也是这样的，卡那里了
希望能在翻译界面添加一个关闭按钮，手动关闭弹出的翻译框！

**Comment by lmk123** [comment]
加入关闭按钮已经在开发计划当中
