### ISSUE TITLE
默认设置英译中

### ISSUE THREAD

**Issue by fimmugit** [Selection-Translator/crx-selection-translate#409]
我从options里未能找到用户如何设置英译中，每次使用都要选，比较麻烦。作者能否添加默认语言1（如英语）->语言2（如中文），这样方便大家。印象中原来可以的，但现在不行。

**Comment by lmk123** [comment]
你指的应该是 #358 这个问题吧。

**Comment by fimmugit** [comment]
我的版本是6.3.4，默认用的是谷歌（国外）翻译，划词英译中时，不能自动判断，只有英文没有翻译，每次需要选择语言才能翻译，与#358的问题一样。本人在美国。
    On Wednesday, April 18, 2018, 10:53:09 PM EDT, mingkaili <notifications@github.com> wrote:  
 
 
你指的应该是 #358 这个问题吧。
