### ISSUE TITLE
有道翻译接口过期了

### ISSUE THREAD

**Issue by Sinspiren** [Selection-Translator/crx-selection-translate#411]
一直挺好用的谢谢作者

我是6.3.4， 最近出现这个， 很久了一直都没好，不知道为什么，是我设置有问题吗？ 
坐标加拿大

**Comment by niconical** [comment]
either

**Comment by Sstrawer** [comment]
这个问题我发现是在调用 "翻译网页中选中的文本：Alt + A" 时触发
触发条件:选中的单词末尾有一个空格

**Comment by lmk123** [comment]
有道翻译的接口过期了我还没有更新……

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你们可以手动更新后试一下，有问题欢迎反馈！
