### ISSUE TITLE
在触摸屏 Win 10（Surface Pro）里 Chrome 66 浮窗不会自动消失

### ISSUE THREAD

**Issue by justwezzz** [Selection-Translator/crx-selection-translate#412]
# 作者更新：

升级至 v6.4.1 及以上版本即可。

-------

现象
chrome66中查询完一次后，结果框不消失，无法查询第二次。

环境
win10 1709
chrome 66.0.3359.117（正式版本） （64 位）

**Comment by lmk123** [comment]
无法重现。能提供更多信息吗？例如在哪个网页出现的、使用何种翻译接口等等？

**Comment by hentaicreep** [comment]
任意网页，任意翻译接口，都会出现这个问题，问题截图如下：
![1](https://user-images.githubusercontent.com/1901634/38972148-72827528-43d1-11e8-8751-162a5935c0ad.png)

![2](https://user-images.githubusercontent.com/1901634/38972156-7a34870c-43d1-11e8-875d-8017cbaf4692.png)

**Comment by hentaicreep** [comment]
补充下，这个问题在chrome 65下无法重现，好像就是这次升级到66的时候出现的问题。

**Comment by lmk123** [comment]
macOS 下 Chrome 66 无法重现，我回去了用 Windows 试试

**Comment by klzsysy** [comment]
me too，update to chrome 66，windows 10 1709 x64

**Comment by lmk123** [comment]
我最近收到大量用户反馈这个问题，明天（2018 年 5 月 7 日）晚上我会找台 Windows 电脑看一下。

**Comment by 2xin-zh** [comment]
浏览器升级之前是没有问题的，升到66才这样的，希望尽快解决，突然感觉好不方便啊~

**Comment by Fearyfire** [comment]
尤其是chrome打开PDF的时候进行划词操作，浮窗不会消失，持续了好几个版本了。。

**Comment by hezlog** [comment]
Google Chrome
Google Chrome 已是最新版本
版本 66.0.3359.139（正式版本） （64 位）

OS：win10 x64

github.com 任意划词 出现“译”按钮点击无反应。

**Comment by lmk123** [comment]
Hi 各位，我需要大家的帮助。

我在自己的 Win 10 电脑上将划词翻译更新至 6.4.0 并且将 Chrome 更新至版本 66.0.3359.170（正式版本）（64 位），重启浏览器后**一切正常**。

鉴于我这边无法重现这个问题，所以我希望大家能按照下面的步骤帮助我收集错误信息：

1. 打开 https://github.com
2. 随便翻译几个单词，**展开翻译框的设置区并截图发在这里**
3. 点击浏览器地址栏右侧的菜单 -> 更多工具 -> 开发者工具，将浏览器下方出现的选项卡切换到 Console，如果 Console 里有红色的错误，请**将内容截图留言发到这里**
4. 然后点击菜单 -> 更多工具 -> 扩展程序，找到划词翻译并点击「详细信息」->「背景页」，将弹出来的窗口选项卡切换到 Console，如果 Console 里有红色的错误，请**将内容截图留言发到这里**

示例：

![image](https://user-images.githubusercontent.com/5035625/39932705-735609ca-5573-11e8-9d5b-dcb63555417d.png)

![image](https://user-images.githubusercontent.com/5035625/39932599-2740b5b2-5573-11e8-8ff8-23d8db6b7a2a.png)

另外，如果你出现了这个问题，可以尝试删除划词翻译后重装，如果重装后一切正常，也请在这里留言告知我。

谢谢大家！

**Comment by hentaicreep** [comment]
![1](https://user-images.githubusercontent.com/1901634/39966340-e11da50c-56dc-11e8-8931-e11a788252b5.png)

背景页：
![default](https://user-images.githubusercontent.com/1901634/39966343-ee1de0d2-56dc-11e8-9559-106264bc2bd8.png)

也尝试过重装插件，但是并没有效果。

**Comment by jmdsqs** [comment]
我重装了都没效果。控制台里面都没有红色的错误。而且双击翻译第一个词可以，然后双击第二个词就不会翻译了。

**Comment by jmdsqs** [comment]
而且翻译完了窗口不会消失。

**Comment by jmdsqs** [comment]
win10 版本：1803
chrome 版本： 66.0.3359.139（正式版本） （64 位）

**Comment by jmdsqs** [comment]
![gif](https://user-images.githubusercontent.com/28215980/39978944-fbadfa68-5775-11e8-88d8-655ceabcf7b4.gif)

**Comment by jmdsqs** [comment]
![snipaste_2018-05-14_13-02-44](https://user-images.githubusercontent.com/28215980/39979316-50fc1552-5778-11e8-9fc4-dc0f03cafa71.png)

**Comment by lmk123** [comment]
@hentaicreep @jmdsqs 我注意到你们两个的浏览器版本跟我的是不一致的，你们能不能尝试将浏览器升级到 66.0.3359.*170* 再试试？

**Comment by hentaicreep** [comment]
@lmk123 升级到66.0.3359.170还是一样的问题，我用隐私模式只开启划词翻译插件，其他插件全关闭，也还是不行，操作系统升级到了1803也不行。

**Comment by jmdsqs** [comment]
@lmk123  刚刚升级了，情况是一样的。

**Comment by jmdsqs** [comment]
不过背景页的控制台没有了红色的那些提示。也就是两个地方的控制台都没有红色提示。我感觉我上面那个图提供的红色提示应该是网络波动的问题吧。

**Comment by lmk123** [comment]
无法重现的问题最是麻烦……我晚上回去再试试

**Comment by 2xin-zh** [comment]
是不是Chrome退回65是就行了？

**Comment by lmk123** [comment]
@2xin-zh 应该是的，你可以试试

**Comment by justwezzz** [comment]
反馈一个奇怪的现象，先上gif图
![test](https://user-images.githubusercontent.com/1901634/40093623-a75c06cc-58f5-11e8-81a6-6fcc599e3c4f.gif)
我发现在chrome的设置页面里，失焦事件很奇怪，感觉是触发了，但是后来又还原了。我记得之前的版本里，点击设置页空白区域，是可以关闭设置窗口的，但是现在不行了。不知道是不是chrome的这个问题导致了划词翻译的某些事件无法触发？

**Comment by xiehuiAndroid** [comment]
![qq 20180516142840](https://user-images.githubusercontent.com/8916571/40100232-ce77ca1e-5915-11e8-9103-2e4be48c6573.jpg)
点击不会翻译，失去焦点，也不会自动消失
![qq 20180516143042](https://user-images.githubusercontent.com/8916571/40100237-d4032852-5915-11e8-9388-ff5ce362ac06.jpg)
鼠标右键翻译的，翻译完不消失
win 10  1803，chrome：版本 66.0.3359.181（正式版本） （64 位）
插件是卸载后重装的
个人电脑好像是 chrome 65升66版本后出现的，公司电脑没有这个问题

**Comment by hezlog** [comment]
我尝试清除浏览器数据，更新最新版，关闭其他所有插件，都没有效果。

Google Chrome 版本 66.0.3359.181（正式版本） （64 位）
OS：win10 1803 家庭版 x64

故障：
github.com 任意划词 出现“译”按钮点击无反应。

控制台也不报错误。

**Comment by 2xin-zh** [comment]
退回65版本一切正常，等修复了我再升级最新版吧
版本 65.0.3325.181（正式版本） （64 位）

**Comment by GabrielchenCN** [comment]
我也是同样的问题，浏览器升级之后有道翻译也出问题了。没想到这个插件也有问题。
系统:Windows 10
浏览器:Version 66.0.3359.181 (Official Build) (64-bit)
暂时可以手动 `Esc` 关闭窗口

**Comment by yoooooooo** [comment]
![test](https://user-images.githubusercontent.com/7183018/40371844-f5c9e5ca-5e15-11e8-8cb7-9f1faddb9994.gif)
@lmk123

**Comment by lmk123** [comment]
@yoooooooo 感谢提供如此详细的问题出现过程！我现在有一个大致的排错方向了

**Comment by smallAunt** [comment]
我之前一直有这个问题，今天下午突然bug消失了。(5/26)
三点打开浏览器时还有问题，5点多在新打开的界面突然恢复正常。
看了下浏览器和扩展程序均未有更新。
chrome 66.0.3359.181, 划词翻译 v6.4.0.
看了下唯一区别是win10由10.0 16299.248更新到了16299.431.
但看了下貌似是20号就更新了，好像没关系。
也是没想通，姑且汇报下。。。至少存在我这种莫名自动恢复正常的例子。

**Comment by justwezzz** [comment]
升级到chrome 67（64位）问题依旧存在

**Comment by MoCongxin** [comment]
@lmk123 我发现这个 bug 出现的原因了，开一个新窗口，不是新标签页，就会出现这个问题。

推测是 background 没有好好的作用到新窗口。

**Comment by RoamIn** [comment]
+1

**Comment by lxfly2000** [comment]
Win10 Chrome 67.0.3396.99 同样问题

**Comment by lxfly2000** [comment]
我发现这个问题与触控屏有关，在有触控功能的电脑上就会出现这个问题，暂时的解决方法是禁用触控：打开设备管理器，人体学输入设备，符合HID标准的触摸屏，选择禁用设备。目测是Chrome的锅，不过也建议作者对触控屏优化一下。

**Comment by lxfly2000** [comment]
或者在`chrome://flags`里禁用 Touch Events API

**Comment by xiehuiAndroid** [comment]
@lxfly2000 电脑触控屏，用了你的方法后确实可以了，感谢！

**Comment by RoamIn** [comment]
@lxfly2000 It works !

**Comment by justwezzz** [comment]
@lxfly2000 飞哥牛逼！

**Comment by lxfly2000** [comment]
@justwezzz 不要乱给人家起外号

**Comment by UlyssesWu** [comment]
同样是触屏用户遇到此问题，希望作者大大能做些优化。

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
我的是100%自动固定 这BUG真呛人

**Comment by NyaMisty** [comment]
是不是可以考虑加一下event？我在调试器里看了一下确实mousedown消息没有收到

**Comment by lxfly2000** [comment]
@lmk123 作者您不打算修复这个问题了吗，都指出问题原因了也没见个回复

**Comment by scott-ho** [comment]
![image](https://user-images.githubusercontent.com/35443789/45193703-fc680180-b281-11e8-942e-752fc62a6b86.png)

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
我已经放弃用这个扩展了,
现在用https://github.com/waynecz/dadda-translate-crx
省的这么麻烦，抛弃你的感觉真的难受！

**Comment by RoamIn** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 
 楼上有个触屏电脑的解决方法，不知道你试过没，我是解决了。

**Comment by lxfly2000** [comment]
@lmk123 是，不过要复现这个问题也没必要换有触屏的电脑，你就把Touch Events API选项强制开启选Enabled就行了，我目前想到的解决思路有两个，一是看mousedown事件是不是被触摸事件拦截了，拦截的话就把mousedown事件转到那个触摸事件中处理，二是想办法避免触发触摸事件。
总之希望能尽快修复这个问题，毕竟挺好用的插件因为这个问题流失触屏用户也不值得。

**Comment by lmk123** [comment]
我刚发布了 6.4.1 版本解决了这个问题，由于我手头没有真正的触屏版 Windows，希望大家升级之后给我一些反馈，谢谢。

**Comment by justwezzz** [comment]
升级后无法使用了，不管是划词还是按住ctrl，都没有一点反应。
![1](https://user-images.githubusercontent.com/1901634/45870372-51952e80-bdbd-11e8-9501-f4b7e8d5d573.png)
![test](https://user-images.githubusercontent.com/1901634/45870380-5528b580-bdbd-11e8-87bf-ed0c20bfabf5.gif)

**Comment by UlyssesWu** [comment]
同上，只能通过邮件菜单手动翻译，而且翻译框仍然无法关闭（点击页面空白处不会关闭翻译框。为何不能加个x按钮？）。

**Comment by weekano** [comment]
同上，通过鼠标划词没有反应，只能通过右键来选择翻译，同时翻译后的对话框自己不会消失，只能刷新网页；用win7系统的触屏的话可以划词出现翻译的对话框，但对话框也不会自动关闭

**Comment by lmk123** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 达达翻译不会有这个问题吗？达达翻译是我同事开发的，如果他的是正常的，那我问问他是怎么做的 😂

**Comment by lxfly2000** [comment]
升级到6.4.2后直接就不能用了。作者你要是没有触摸屏电脑的话只需把Touch Events API选项强制开启就行了。达达翻译没有这个问题。

**Comment by chenxuuu** [comment]
哇@lxfly2000 这个方法。。。普通电脑进`chrome://flags`把`Touch Events API`改成`enable`也能复现这个问题了
@lmk123 可以试试🤣

**Comment by weekano** [comment]
看了上面的评论，果断在我win7带触摸屏的thinkpad T450s电脑里打开chrome://flags把Touch Events API改成disable，现在鼠标点击翻译插件终于正常了！  如果触摸屏的笔记本电脑实际操作肯定还是鼠标啊

**Comment by justwezzz** [comment]
最新版本问题解决了，thx😃
