### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by Lane1196** [Selection-Translator/crx-selection-translate#415]
1、百度翻译、必应翻译始终提示“稍后再试”
2、谷歌翻译、谷歌翻译（国内） 输入中文翻译  无法自动识别翻译成 英文

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你可以手动更新后试一下，有问题欢迎反馈！谷歌的问题可以关注 #358 查看后续。
