### ISSUE TITLE
Feature request: 希望翻译弹窗中能显示单词音标

### ISSUE THREAD

**Issue by DOTA2mm** [Selection-Translator/crx-selection-translate#417]
> 首先感谢作者的殷勤付出。
希望能在弹窗中加入英文的英标，使用过程中可能不会经常听发育，但是看一眼音标知道读音，感觉可以加深对单词的印象有助于记忆。

**Comment by lmk123** [comment]
在 v6.4.0 中使用百度翻译就可以看到音标了。其他翻译接口没有返回音标所以无法显示。
