### ISSUE TITLE
翻译界面一直固定，不会自动消失。

### ISSUE THREAD

**Issue by disheng008** [Selection-Translator/crx-selection-translate#420]
翻译界面一直固定，不会自动消失。

**Comment by lmk123** [comment]
macOS Chrome 66 无法重现，提供一下更多信息？如操作系统、出现问题的网址、划词翻译版本等等

**Comment by lmk123** [comment]
会不会是因为安装了某些脚本导致的？例如 https://github.com/Selection-Translator/crx-selection-translate/issues/400#issuecomment-374905046

**Comment by kmon25** [comment]
我也遇到同樣的問題 請問怎麼解決呢
覺得這個套件非常好用 不想移除

**Comment by birdfly** [comment]
我试着把所有脚本都禁用，只留了“划词翻译”，该现象依旧无法解决。
版本 66.0.3359.139（正式版本） （64 位）
Windows 10 1803（17134.5）
划词翻译版本v6.4.0
所有网址划词翻译都无法正常工作

**Comment by chesterlp** [comment]
我也一样，顺路寻找到了这里，特意反馈。
版本 66.0.3359.139（正式版本） （64 位）
划词翻译版本v6.4.0
WIN10

**Comment by smallAunt** [comment]
一样，点“译”字后，就像卡死一样没反应也无法消失了。
可能是chrome更新后出现的(不确定)，建议检查下是否和chrome的新版本有关。
划词翻译 v6.4.0
Chrome 66.0.3359.139（正式版本） （64 位）
win 10.0 16299.248

**Comment by fulvaz** [comment]
我的问题是是网络不好的时候, 没有返回结果, 然后一直处于加载状态, 提示框无法关闭

**Comment by bagualing** [comment]
同@smallAunt一样的问题，出现“译”字后，卡死，无反应，网页可以正常浏览。

**Comment by harry0071** [comment]
chrome升级到 66.0.3359.13964 位）同样遇到这个问题 
划词翻译后，点击页码其他地方，无法关闭翻译框，翻译框一直固定在页面上

**Comment by lmk123** [comment]
看起来跟 #412 是重复的
