### ISSUE TITLE
现在有道、百度、必应翻译都不能用了，谷歌的国内支持也不好

### ISSUE THREAD

**Issue by jyliao** [Selection-Translator/crx-selection-translate#422]
现在有道、百度、必应翻译都不能用了，谷歌的国内支持也不好
基本划词翻译可以是个摆设了，可以做回之前的版本有道key那版本吗。 自己申请一个key翻译速度很快。 现在基本什么都翻译不出来了

**Comment by lmk123** [comment]
有道翻译收费了，所以没有加 key 了。

等我有空了我更新一下内部的翻译功能的版本吧

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译不再支持，你可以手动更新后试一下，有问题欢迎反馈！

**Comment by reaCodes** [comment]
@lmk123 请问啥时候可以更新v6.4.0？现在应用商店的版本还是v6.3.4

我个人平时比较依赖这个插件，作者可以考虑推出收费版本或者项目，用来帮助愿意花钱的用户提升体验

**Comment by lmk123** [comment]
现在更新成 v6.4.0 了，试试看。

我正在开发新版本，同时也有考虑过收费版本的问题，但是精力有限，出新版不知道要到什么时候了

**Comment by veeson** [comment]
感谢作者，Chrome自动更新到v6.4.0版本之后有道和百度翻译都能用了。
