### ISSUE TITLE
使用有道查询suboptimal 这个单词总是报错

### ISSUE THREAD

**Issue by a819721810** [Selection-Translator/crx-selection-translate#424]
使用有道查询suboptimal 这个单词总是报错，查询其他单词没问题，目前就发现这一个

![image](https://user-images.githubusercontent.com/10041362/39558400-e88a728a-4ec0-11e8-82e0-51c2576ee000.png)
![image](https://user-images.githubusercontent.com/10041362/39558523-d73e676a-4ec1-11e8-838c-7d5178e9f861.png)

![image](https://user-images.githubusercontent.com/10041362/39558411-01f6a2fc-4ec1-11e8-91b2-bb1d2f72f54b.png)

而其他的三个翻译都不会报错

**Comment by lmk123** [comment]
我在 http://fanyi.youdao.com/ 里试了一下，这个单词也是翻译不出来的，所以这是有道翻译的问题，我这边无法修复。

**Comment by a819721810** [comment]
![image](https://user-images.githubusercontent.com/10041362/39565035-06dbec82-4ee9-11e8-8ee2-899e44fadeca.png)
有道不是可以翻译出来吗

**Comment by lmk123** [comment]
能翻译出来是因为你手动选择了翻译方向为「英语 > 中文」，你把它改成「自动检测」就翻译不出来了。在划词翻译里默认就是用的自动检测，除非你手动选择翻译语言。
