### ISSUE TITLE
浮窗卡在网页上无法消失

### ISSUE THREAD

**Issue by baishuijianjia** [Selection-Translator/crx-selection-translate#426]
进入网页之后鼠标随意划一下，再点其它地方，本该消失的浮窗无法消失

**Comment by lmk123** [comment]
macOS 10.13.4 & Chrome 66.0.3359.139（正式版本）（64 位）无法重现，你的环境是什么？

**Comment by lmk123** [comment]
看起来跟 #420 是重复的。
