### ISSUE TITLE
浮窗不会消失的问题

### ISSUE THREAD

**Issue by Fearyfire** [Selection-Translator/crx-selection-translate#427]
打开一个网页进行第一次划词操作之后，弹出浮窗，取消划词，浮窗不会消失，换新的单词进行划词，浮窗不会更新，之前久的划词的浮窗一直存在，只有刷新才会消失，但是复制一个单词，点机工具栏的按键，会正常弹出翻译结果，但是第一划词的浮窗依旧不会消失，不知道这个bug是什么原因，如果作者有时间的话可以修复一下，之前软件一直特别好用，给了我很大的帮助，十分感谢！！！

**Comment by lmk123** [comment]
#412
