### ISSUE TITLE
默认快捷键Ctrl+Q无法彻底删除

### ISSUE THREAD

**Issue by GH01** [Selection-Translator/crx-selection-translate#428]
在Chrome的扩展管理中，删除“划词翻译”的快捷键Ctrl+Q，
关掉再打开扩展管理，此快捷键又在了。

**Comment by lmk123** [comment]
还真有这个问题，不过删除后快捷键其实已经失效了，只是还显示在那里，看起来像是新版 Chrome 的问题，我这边看看能不能做点什么避免这个问题

**Comment by reaCodes** [comment]
找到了设置快捷键的地方，`chrome://extensions/shortcuts`，删除了这个快捷键之后还会出现在这里，不过已经不起作用了

---
![image](https://user-images.githubusercontent.com/13817254/39963608-39af1c12-56a3-11e8-95a0-2a12ce9bcb73.png)

**Comment by GH01** [comment]
这个问题能否尽早解决？
Ctrl+Q是个方便的快捷键，被占据了实在可惜。
还是该由Vivaldi解决？

**Comment by GH01** [comment]
我笨了，换个不用的按键，不就把Ctrl+Q解放了吗！

P.S.
凡自带默认快捷键的扩展在Chrome中好像都会有此问题。
