### ISSUE TITLE
觸碰螢幕的筆電 無法使用滑鼠點擊 "譯"

### ISSUE THREAD

**Issue by mtf77223** [Selection-Translator/crx-selection-translate#431]
作者你好!  有使用的問題要反映。
目前我筆電acer swift5 (sf514-52t) 有觸碰螢幕
使用 chrome版本 66.0.3359.181 (正式版本) (64 位元)
無法使用滑鼠點擊 "譯" 只有觸碰螢幕後才能跑出翻譯視窗。
不過我也發現到，像是專利the lens的網站，在看圖的時候他也只能靠觸碰螢幕去點才可以翻頁...
以及與很多使用者有同樣的問題 這個 "譯" 無法自動消失。

看來這次chrome改版問題多多啊....

**Comment by hezlog** [comment]
我也是相同问题，Yoga720，目前无解决办法。

**Comment by mtf77223** [comment]
忘記說 
希望作者未來可以加入繁體中文的顯示! 
這小工具對我來說真的是太好用了!

**Comment by lmk123** [comment]
你好，我做完发布了 v6.4.2 版本，完善了对触屏设备的支持，你可以试一下还有没有这个问题，很希望能得到你的反馈！

**Comment by lmk123** [comment]
#412 已解决
