### ISSUE TITLE
点击“译”字无反应，且“译”字卡在该位置无法消失。

### ISSUE THREAD

**Issue by smallAunt** [Selection-Translator/crx-selection-translate#432]
点“译”字后，就像卡死一样没反应，“译”字也无法消失也无法移动位置，且在该页面划其他词不在有反应。

可能是chrome更新后出现的(不确定)，建议检查下是否和chrome的新版本有关。
划词翻译 v6.4.0
Chrome 66.0.3359.139（正式版本） （64 位）
(现更新为66.0.3359.181，依然存在问题)
win 10.0 16299.248

关闭其他插件，以及在隐身模式下只开启了划词翻译一个插件依然存在问题。
重装无法解决问题。
F12控制台无报错信息：
![image](https://user-images.githubusercontent.com/15324929/40295866-7d9095d0-5d0d-11e8-821e-e9287aae8925.png)

**Comment by lmk123** [comment]
重复 #412 

我这边无法重现，有用户反馈退回 Chrome 65 就正常了

**Comment by smallAunt** [comment]
看到了那个issue，我以为不是一个问题呢。
刚发现关闭了“划词后显示翻译按钮”的话是#412的问题，只是开启了该功能会呈现我描述的现象。
谢谢了。
