### ISSUE TITLE
在百分浏览器下失效

### ISSUE THREAD

**Issue by SoDa-GitHub** [Selection-Translator/crx-selection-translate#437]
百分浏览器
Version 3.4.3.39 (Official Build) (64-bit) (Chromium 66.0.3359.181)

划词翻译
v6.4.0

Windows
Version 10.0.17134.81

划词->点击“译”->没反应

**Comment by jizf1984** [comment]
我现在chrome下都点不开 译 字。不晓得是什么问题。

**Comment by lmk123** [comment]
重复 #412
