### ISSUE TITLE
win10 Chrome 版本 67.0.3396.79（正式版本） （64 位） 无法正常使用

### ISSUE THREAD

**Issue by xhanglizhu** [Selection-Translator/crx-selection-translate#440]
win10 Chrome 版本 67.0.3396.79（正式版本） （64 位） 无法正常使用
Chrome升级之前正常，升级到最新的无法使用，主要表现：
在页面上选择语句之后，点击“译”，不显示翻译框，“译”字也不消失。

**Comment by lmk123** [comment]
#412 重复
