### ISSUE TITLE
PDF在chrome上打开后滑词无法使用

### ISSUE THREAD

**Issue by hugoliu1984** [Selection-Translator/crx-selection-translate#443]
pdf在chrome上打开以后，段落翻译不了，版本也是最新版本。
![image](https://user-images.githubusercontent.com/40561060/41841642-6a155d8e-789b-11e8-8b1b-ebc8177d4f01.png)

**Comment by iris0329** [comment]
我也有这个问题！！！

**Comment by lmk123** [comment]
在扩展程序设置里勾选「允许访问文件网址」

**Comment by hugoliu1984** [comment]
抱歉，才看到，重新安装以后没有了，多谢了！------------------ 原始邮件 ------------------发件人: mingkaili <notifications@github.com>发送时间: 2018年11月8日 19:02收件人: Selection-Translator/crx-selection-translate <crx-selection-translate@noreply.github.com>抄送: hugoliu1984 <Lxiao1994@gmail.com>, Author <author@noreply.github.com>主题: 回复：[Selection-Translator/crx-selection-translate] PDF在chrome上打开后滑词无法使用 (#443)在扩展程序设置里勾选「允许访问文件网址」—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.发自我的iPhone------------------ 原始邮件 ------------------发件人: mingkaili  <notifications@github.com>发送时间: 2018年11月8日 19:02收件人: Selection-Translator/crx-selection-translate <crx-selection-translate@noreply.github.com>抄送: hugoliu1984 <Lxiao1994@gmail.com>, Author <author@noreply.github.com>主题: 回复：[Selection-Translator/crx-selection-translate] PDF在chrome上打开后滑词无法使用 (#443)在扩展程序设置里勾选「允许访问文件网址」

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Selection-Translator/crx-selection-translate","title":"Selection-Translator/crx-selection-translate","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Selection-Translator/crx-selection-translate"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lmk123 in #443: 在扩展程序设置里勾选「允许访问文件网址」"}],"action":{"name":"View Issue","url":"https://github.com/Selection-Translator/crx-selection-translate/issues/443#issuecomment-436956679"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Selection-Translator/crx-selection-translate/issues/443#issuecomment-436956679",
"url": "https://github.com/Selection-Translator/crx-selection-translate/issues/443#issuecomment-436956679",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Selection-Translator/crx-selection-translate] PDF在chrome上打开后滑词无法使用 (#443)",
"sections": [
{
"text": "",
"activityTitle": "**mingkaili**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lmk123",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Selection-Translator/crx-selection-translate\",\n\"issueId\": 443,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Selection-Translator/crx-selection-translate/issues/443#issuecomment-436956679"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349642217\n}"
}
],
"themeColor": "26292E"
}
]
