### ISSUE TITLE
音标和界面。

### ISSUE THREAD

**Issue by DreamRainInFlowingTime** [Selection-Translator/crx-selection-translate#451]
1、可以有音标么。没音标读不好。
2、绿色的部分可以改少么。看着很难受。像ChaZD插件或者有道插件那样，感觉ChaZD就很舒服。

**Comment by DreamRainInFlowingTime** [comment]
3、卡。一开始用着还不卡，后来咋和ChaZD的程度差不多。。查不出来。

**Comment by lmk123** [comment]
百度有音标，其它的没提供
界面和性能会在新版本优化。
