### ISSUE TITLE
建议反馈，修改背景颜色。

### ISSUE THREAD

**Issue by MrCaoTong** [Selection-Translator/crx-selection-translate#454]
能否加入一个修复弹窗背景颜色的功能，当个人不是很喜欢默认配色时，希望能让用户在设置界面手动修改颜色。

**Comment by MrCaoTong** [comment]
另外，能否加入一个修复弹窗背景颜色的功能，当个人不是很喜欢默认配色时，希望能让用户在设置界面手动修改颜色。

**Comment by lmk123** [comment]
新版会调整样式的
