### ISSUE TITLE
无法隐藏扩展按钮？

### ISSUE THREAD

**Issue by GH01** [Selection-Translator/crx-selection-translate#457]
我用Vivaldi浏览器，最近几版以来，“划词翻译”的扩展按钮无法隐藏。
猜想是Chrome内核更新导致的。
您能否在Chrome中试一下？
如果不是Chrome的原因，那我再向Vivaldi反馈。

**Comment by lmk123** [comment]
我在 Chrome 中可以正常隐藏和显示。

![image](https://user-images.githubusercontent.com/5035625/43241506-3b584d58-90ce-11e8-8b68-70617831da9b.png)

**Comment by GH01** [comment]
搜了Vivaldi官坛才明白，原来是它的Extension Toggle设计改变了：
https://forum.vivaldi.net/post/218271
https://forum.vivaldi.net/post/218278

▲启用Extension Toggle，则各扩展按钮无法单独隐藏，只能用Extension Toggle整体显隐。
▲停用Extension Toggle，则各扩展按钮可以单独隐藏，此时Extension Toggle充当下拉按钮（类似Chrome）。

未见Changelog明确提到，也许还在改进中。

@lzm956902416

**Comment by lzm956902416** [comment]
thx
