### ISSUE TITLE
接口每天都会报错

### ISSUE THREAD

**Issue by kzihong** [Selection-Translator/crx-selection-translate#461]
使用了两天，每天用了一段时间之后就不能用了，翻译什么内容都是“接口返回了错误的数据，请稍候重试。”

**Comment by lmk123** [comment]
我试了一下，所有接口都没有出现你说的问题，你是哪个接口出问题了？

**Comment by kzihong** [comment]
![image](https://user-images.githubusercontent.com/17907809/43365973-bf4a363a-9367-11e8-8d5d-0d5abca82478.png)

**Comment by Apppt** [comment]
坐标日本，同样出现这样的问题。

**Comment by FENGHE123** [comment]
坐标杭州，使用国内谷歌翻译报错

**Comment by lmk123** [comment]
我也遇到了，使用谷歌国内接口时被 Google 判定为异常流量给禁了 😂但似乎过一段时间就会解封。

我想想看我这边能不能做点什么避免划词翻译发起的请求被封

**Comment by lmk123** [comment]
后续谷歌翻译的的进度统一更新到 #500
