### ISSUE TITLE
（不关闭设置窗）直接关闭扩展页面 导致该进程崩溃（Vivaldi?）

### ISSUE THREAD

**Issue by GH01** [Selection-Translator/crx-selection-translate#470]
打开扩展页面，再打开设置窗。（在浮窗中点击齿轮 同理）
此时，不关闭设置窗，直接关闭扩展页面，该进程崩溃。

▲因为我有监控软件在运行，报有dmp生成：
C:\Users\*\AppData\Local\Vivaldi\User Data\Crashpad\reports\*.dmp
所以确知是崩溃。

我用的是Vivaldi。
麻烦您在Chrome中试一下。

**Comment by lmk123** [comment]
试了一下，没有任何问题。

你这边进程崩溃了之后会导致划词翻译不可用吗？

**Comment by GH01** [comment]
不会，仍然可用。
所有设置项（除了重启项）按设计都是立即生效的吧？

那我向Vivaldi反馈。

**Comment by GH01** [comment]
所有用这种方式（在扩展页中弹出设置窗）的扩展都会遭遇此问题。
所以应该是Vivaldi的bug，已反馈。

**Comment by GH01** [comment]
Vivaldi已修复。
我想此问题可以关闭了。

**Comment by lmk123** [comment]
赞
