### ISSUE TITLE
在chrome 预览pdf时候，翻译有一点对齐问题

### ISSUE THREAD

**Issue by WongYueKeung** [Selection-Translator/crx-selection-translate#479]
比如这个：
[Mosquito Tracking System Case Study.pdf](https://github.com/Selection-Translator/crx-selection-translate/files/2342463/Mosquito.Tracking.System.Case.Study.pdf)
使用chorme预览这个文件，随便选择几句，就会有选择文字时的对齐问题，这是个很常见的文件，测试过很多其他随随便便的PDF文件，包括自己创建一个PDF，
可以正常划词翻译，但是有一定程度上的对齐问题，在划词的时候就会很困难
这个不好描述，自己体会下，不过划词翻译的时候对齐问题还算是有点严重的，划词的时候不知道自己划了啥，值得修复一下。。。

**Comment by CHN-STUDENT** [comment]
@lmk123 
再次在最新版版本版本中发现相同的问题？请问这还是bug嘛？

**Comment by lmk123** [comment]
我会尝试升级一下内置的 PDF 阅读器，看看还有没有这个问题
