### ISSUE TITLE
建议搞两种机制，类似黑名单白名单...

### ISSUE THREAD

**Issue by hakw77** [Selection-Translator/crx-selection-translate#480]
插件现在默认是所有网站启用划词翻译，然后设置“例外网站”禁用划词翻译。
能否让用户选择“禁用所有网站使用划词翻译”，然后设置“例外网站”启用。
毕竟用户还是浏览本国语言网站的时候居多。

**Comment by lmk123** [comment]
这个已经在计划当中了 #259
