### ISSUE TITLE
在Chrome 69版本PDF划词翻译复制和搜寻可能存在问题

### ISSUE THREAD

**Issue by CHN-STUDENT** [Selection-Translator/crx-selection-translate#486]
![image](https://user-images.githubusercontent.com/21209416/45592490-5616ad00-b9a1-11e8-969e-4f49427be8a2.png)
![image](https://user-images.githubusercontent.com/21209416/45592491-5adb6100-b9a1-11e8-8569-8e5bcd494860.png)

**Comment by lmk123** [comment]
已知问题，下次会升级一下内置 pdf 解析器的版本，再看看有没有这个问题

**Comment by CHN-STUDENT** [comment]
这应该是类似问题，希望尽快更新：
https://github.com/Selection-Translator/crx-selection-translate/issues/479

谢谢！
