### ISSUE TITLE
滑词不好用了，点击反应按钮图标没反应

### ISSUE THREAD

**Issue by weekano** [Selection-Translator/crx-selection-translate#487]
![123](https://user-images.githubusercontent.com/35332940/45729634-f4a04980-bbff-11e8-98fd-9ad82e6ef4f9.png)

**Comment by lmk123** [comment]
你提供的信息太少了，你是在哪个 URL 里划词出的问题？滑的是哪个单词？

**Comment by weekano** [comment]
> 你提供的信息太少了，你是在哪个 URL 里划词出的问题？滑的是哪个单词？

所有的URL都出现了，之前出现过一次 后来把Chrome卸载重装了好了，现在又无缘无故的出现了。就是无论点击什么单词翻译都没有单出来翻译框，右键选择翻译的时候可以弹出来翻译框，但是不会自动关闭这个框
![123](https://user-images.githubusercontent.com/35332940/45737924-abf98800-bc21-11e8-95c6-d547402e43a9.png)

**Comment by lmk123** [comment]
你的设备是 Surface 吗？如果是，那就是跟 #412 一样的问题
