### ISSUE TITLE
划词后不显示翻译信息，复现方式不明

### ISSUE THREAD

**Issue by chenxuuu** [Selection-Translator/crx-selection-translate#491]
拓展版本6.4.2，印象中时一个月前开始，在这台电脑上无法显示的，重装插件、浏览器，甚至重装系统后，问题依旧存在。
但是，这个问题只出现在了我的surface pro4上面，工作用的笔记本和老笔记本使用相同的系统和浏览器版本，并未出现该问题

浏览器信息如下：

Vivaldi | 2.0.1309.17 (正式版本) （64 位）
-- | --
修订版本 | 9aa7f74440fd133ef536d2ca3eaeabb09e0685e2-refs/heads/master@{#588962}
操作系统 | Windows
JavaScript | V8 6.9.427.23
Flash | （已停用）
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.102 Safari/537.36 Vivaldi/2.0.1309.17
命令行 | "C:\Program Files\Vivaldi\Application\vivaldi.exe" --flag-switches-begin --flag-switches-end
可执行文件路径 | C:\Program Files\Vivaldi\Application\vivaldi.exe
个人资料路径 | C:\Users\chenx\AppData\Local\Vivaldi\User Data\Default
Linker | lld-link

**Comment by lmk123** [comment]
请关注 #412
