### ISSUE TITLE
有道翻译和官方内容不一样

### ISSUE THREAD

**Issue by cowry5** [Selection-Translator/crx-selection-translate#492]
![tim 20180925103436](https://user-images.githubusercontent.com/32674827/45989513-9f0be700-c0ae-11e8-819c-e90387203767.png)

这是插件翻译的。同样的话，去官网翻译如下，明显官网翻译的好。每次都会出现这样。
![image](https://user-images.githubusercontent.com/32674827/45989522-a8954f00-c0ae-11e8-9f55-ea13f84f520e.png)

**Comment by lmk123** [comment]
接口可能改了，我有空了确认一下

**Comment by lmk123** [comment]
最新版本中此问题已修复
