### ISSUE TITLE
快捷键激活扩展按钮，弹窗在Vivaldi中的独特表现

### ISSUE THREAD

**Issue by GH01** [Selection-Translator/crx-selection-translate#497]
Vivaldi中：
鼠标激活扩展按钮，弹窗在按钮处，正常。
但用快捷键，弹窗却在左上角，如图：
上图为现状，
下图是v6.4，出现在(0,0)处。
![selectiontranslator_vivaldi x y](https://user-images.githubusercontent.com/19272301/46138275-0fb52e00-c27e-11e8-99bb-de42b227b28b.png)

Chrome中没问题。
但在Vivaldi中，其他扩展全没问题。
由您解决还是我报Vivaldi？

**Comment by GH01** [comment]
我倒无所谓，这个几乎不用。
是想向您了解一下，因为其他扩展在Vivaldi中都正常。

P.S.
GitHub的邮件通知常会漏掉一两个，
比如这一批，单这个没收到回复……

**Comment by GH01** [comment]
是您做了修正还是Vivaldi有改动？
6.4.3在最新的Vivaldi(Snapshot)中已正常。

**Comment by lmk123** [comment]
我没有改过这方面的代码，所以我猜是 Vivaldi 做了修复
