### ISSUE TITLE
刚开始用的好好的,突然就翻译失败了,该怎么排查问题呢？

### ISSUE THREAD

**Issue by ZexiFangkong** [Selection-Translator/crx-selection-translate#499]
![iGOeRe.png](https://s1.ax1x.com/2018/10/07/iGOeRe.png)
![iGOmxH.png](https://s1.ax1x.com/2018/10/07/iGOmxH.png)

**Comment by lmk123** [comment]
谷歌翻译确实会间歇性抽风，一般过会儿就会恢复

**Comment by ZexiFangkong** [comment]
好的, 我还以为是我的问题。
