### ISSUE TITLE
希望作者也搞个Firefox版的

### ISSUE THREAD

**Issue by W-quan** [Selection-Translator/crx-selection-translate#50]

**Comment by lmk123** [comment]
我了解过 Firefox Add-on 的开发，相比起来我更喜欢 Chrome extension 的开发方式（几乎跟开发网站是一样的），所以我想在未来的很长一段时间，我都不会考虑开发一个 Firefox 版的划词翻译 :)

**Comment by skyqty** [comment]
Hi, now Firefox 57 has support WebAssembly already, Is it possible to develop?

**Comment by greatghoul** [comment]
https://github.com/HaNdTriX/generator-chrome-extension-kickstart

有试过这种自动转译的吗？可以打包成 Firefox 扩展，但是否有效我没有验证过。

**Comment by lmk123** [comment]
后续同步至 #506

**Comment by lmk123** [comment]
已上架火狐商店。 https://addons.mozilla.org/zh-CN/firefox/addon/hcfy/

如果在火狐里使用遇到问题，欢迎反馈。
