### ISSUE TITLE
求支持火狐，火狐现在可以兼容crx插件

### ISSUE THREAD

**Issue by 1608637229** [Selection-Translator/crx-selection-translate#506]
稍微改改上架火狐应该难度不大吧。

**Comment by zhaoker** [comment]
我也觉得可以考虑下·········· 火狐翻译里面没有一个好用的

**Comment by lmk123** [comment]
新版本会尝试兼容火狐的。

**Comment by lxr0630** [comment]
> 我也觉得可以考虑下···········火福翻译里面没有一个好用的

就是因为火狐上的翻译插件不好用我才不用火狐浏览器的。

**Comment by lmk123** [comment]
已上架火狐商店。 https://addons.mozilla.org/zh-CN/firefox/addon/hcfy/

如果在火狐里使用遇到问题，欢迎反馈。
