### ISSUE TITLE
希望能翻译本地pdf文件

### ISSUE THREAD

**Issue by manyi059** [Selection-Translator/crx-selection-translate#511]
网络上的http协议文件能翻译
本地打开的pdf显示off，无法启用
现在用的时候都是安装一个tomcat，感觉有点麻烦

**Comment by lmk123** [comment]
见[常见问题](https://github.com/Selection-Translator/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BD%95%E5%9C%A8%E6%9C%AC%E5%9C%B0%E6%89%93%E5%BC%80%E7%9A%84-html-%E6%96%87%E4%BB%B6%E5%8D%B3%E4%BB%A5-file-%E5%BC%80%E5%A4%B4%E7%9A%84%E7%BD%91%E5%9D%80%E9%87%8C%E5%A4%B1%E6%95%88)

**Comment by manyi059** [comment]
谢谢，终于知道“允许访问文件网址”是什么意思了
