### ISSUE TITLE
pdf双击选定单词问题

### ISSUE THREAD

**Issue by fengbo4213** [Selection-Translator/crx-selection-translate#512]
打开pdf双击某个单词会选定很多无关的词，而不是固定到想翻译的词上。
![image](https://user-images.githubusercontent.com/8640917/47471606-92a9b400-d83d-11e8-97e8-72b32023d391.png)

**Comment by lmk123** [comment]
我会尝试升级划词翻译内置的 PDF 阅读器看看能不能解决这个问题。
