### ISSUE TITLE
接口返回了错误的数据，请稍候重试。

### ISSUE THREAD

**Issue by zhubenjie** [Selection-Translator/crx-selection-translate#513]
用的是 google翻译， 发音没问题， 但是数据显示不出来。

**Comment by zhubenjie** [comment]
换成 google cn 的时候，翻译次数过快就提示
接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。

**Comment by justwezzz** [comment]
我也遇到这个问题了，只要在短时间连续调用google的接口几十次就会出这个问题。
下面贴个图描述下情况：
1.登录网页版的谷歌翻译，输入“test”查询，可以发现没有报错，结果正常返回：
![1](https://user-images.githubusercontent.com/1901634/47480244-5ccaf680-d862-11e8-9ead-8b4f7bf6dbd8.png)
2.使用翻译插件调用谷歌翻译，此时返回异常：
![3](https://user-images.githubusercontent.com/1901634/47480286-85eb8700-d862-11e8-8eec-309fdc66ff33.png)
对比两者的cookie部分，没发现有区别，header里唯一不同的地方只有get请求的参数。
谷歌翻译网页版的参数：
![2](https://user-images.githubusercontent.com/1901634/47480355-b59a8f00-d862-11e8-870a-75cafe2ea039.png)
插件的参数：
![4](https://user-images.githubusercontent.com/1901634/47480376-c6e39b80-d862-11e8-9c90-b29ef153ef08.png)
没太搞懂谷歌为什么认为插件的请求就是有问题的。原来出现这个问题还会触发reCaptcha机制来验证你不是机器人，现在都不给你证明的机会，直接ban了ip，不知道是不是最近google调整了什么策略哦。

**Comment by lmk123** [comment]
后续进展查看 #500 吧。
