### ISSUE TITLE
能否参考“猎豹翻译”的风格和界面设计

### ISSUE THREAD

**Issue by zkdl** [Selection-Translator/crx-selection-translate#516]
能否参考“猎豹翻译”的风格和界面设计（有可能的话其翻译引擎也囊括进来）
，现在你的扩展始终无法实现页面翻译。
[猎豹翻译_v0.1.1.78.crx.zip](https://github.com/Selection-Translator/crx-selection-translate/files/2536851/_v0.1.1.78.crx.zip)

**Comment by lmk123** [comment]
新版本我会参考一下的。

页面翻译是指翻译整个页面吗？之前划词翻译包含了谷歌、必应和有道的网页翻译，但是总是出问题，所以后来去掉了，建议按照这些网页翻译的说明加个书签来使用。
