### ISSUE TITLE
接口返回了错误的数据，请稍候重试。 

### ISSUE THREAD

**Issue by skalaloo** [Selection-Translator/crx-selection-translate#517]
或
“网络错误，请检查你的网络设置。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。”

尴尬了，我正好偏偏要开vpn的情况下用这个插件的，例如最近behance整个被墙，不得不开全局模式。

**Comment by lmk123** [comment]
开翻墙的时候你用国际版谷歌翻译就好了

**Comment by skalaloo** [comment]
就是选的国际版。。

mingkaili <notifications@github.com> 于2018年11月5日周一 下午2:33写道：

**Comment by lmk123** [comment]
错误信息不是写着“谷歌翻译（国内）”吗？

**Comment by asgg4321** [comment]
今天开着vpn,使用谷歌翻译（国外版）显示接口返回了错误信息，请稍后重试，切换回国内版，恢复功能，不知道具体原因，无法把具体错误进行报告了
