### ISSUE TITLE
当翻译按钮打开的时候，如果一个网页点击过翻译按钮，那么之后就不用显示翻译按钮而是直接显示翻译结果

### ISSUE THREAD

**Issue by zhangchunlin** [Selection-Translator/crx-selection-translate#520]
逻辑是显示翻译按钮的原因是很多页面选择内容的时候并不是想要查词，所以不想要翻译结果的干扰
但如果一个页面查过词，那么之后继续查词的可能性很大，那么每次都要显示翻译按钮就比较不友好

**Comment by lmk123** [comment]
翻译一次后就直接显示结果的话会对复制操作造成更大的影响

**Comment by zhangchunlin** [comment]
@lmk123 不理解
另外是否直接显示结果是一个选项，那么我的这个建议是否也可以作为一个选项，这样想要这个功能的人打开选项就行了？

**Comment by lmk123** [comment]
> 如果一个页面查过词，那么之后继续查词的可能性很大

在我看来，这个“可能性”没有数据支撑，所以我从自己的使用习惯来分析的话，就算我曾经在一个网页上翻译过，但我后面需要一直翻译的“可能性”并没有变大。

如果这个行为习惯看起来并不是常见的，我不会为它增加一个选项。

**Comment by zhangchunlin** [comment]
比如如果在一个中文网页上选中，比较大的可能是复制，此时没有需要查字典，不会点击翻译按钮，我也不希望插件把我的数据发往服务器，所以我会把显示翻译按钮的选项打开
但是如果在阅读一个英文网页，特别是阅读大段英文的时候，需要经常查词，此时每次都要点击翻译按钮很不方便

这种场景一想可知，我认为不需要数据支撑

**Comment by zhangchunlin** [comment]
我只是举个例子，实际情况还有我工作中很多内部英文网站是基本不用查词典的，我也不想把这些网站的信息发往服务端
