### ISSUE TITLE
Chrome上插件无法朗读

### ISSUE THREAD

**Issue by sunshineliang** [Selection-Translator/crx-selection-translate#528]
版本：
Chrome版本：Chrome 70.0.3538.110 ；插件版本：6.4.3；windows 10；
现象：
谷歌翻译无法朗读；弹出窗口后点击”朗读“也不行；

**Comment by sunshineliang** [comment]
@lmk123 每个网页都会，不只是谷歌翻译器，其他的翻译器都会出现。浏览器打开视频网页也有声音。
能不能从代码级别来查找是否有声音？要从浏览器打开控制器，有Network 有无网络请求吗？自己是菜鸟。🤦‍🤦‍🤦‍

**Comment by lmk123** [comment]
如果问题都能从代码级别发现，那也不需要用户反馈了 😂特别是这种你能复现但我不能复现的问题，很有可能是环境不一致导致的，但是我并不知道你那边的运行环境是什么。

提供一下你的浏览器版本号、划词翻译版本、操作系统版本？

**Comment by sunshineliang** [comment]
在浏览器版本 71.0.3578.80（正式版本） （64 位），已经恢复正常啦！
谢谢！
