### ISSUE TITLE
建议翻译整个网页时不翻译网页中的代码块

### ISSUE THREAD

**Issue by AXwjg** [Selection-Translator/crx-selection-translate#542]
因为如果翻译代码块的时候会出现代码块中的格式出现错乱
![image](https://user-images.githubusercontent.com/29494868/50876166-a90be880-1406-11e9-932e-941a26b98415.png)
这是未翻译之前的
![image](https://user-images.githubusercontent.com/29494868/50876180-c04ad600-1406-11e9-8bbd-8c48ef567ae0.png)

**Comment by lmk123** [comment]
你用的不是最新版的划词翻译吧？在最新版中，划词翻译已经去掉了网页翻译的功能，因为内置的网页翻译总是有问题，之后应该也不会对网页翻译的功能做更新维护了。

**Comment by AXwjg** [comment]
😢我现在才发现我原来用的是Chrome自带的网页翻译,并不是划词翻译的网页翻译

**Comment by lmk123** [comment]
😂 看来划词翻译已经好用到是 Chrome 自带的功能了
