### ISSUE TITLE
有道翻译不完整

### ISSUE THREAD

**Issue by alexligoo** [Selection-Translator/crx-selection-translate#549]
![image](https://user-images.githubusercontent.com/26473771/51451101-aa2a0780-1d6e-11e9-9e9c-e4e3fc2ab22c.png)
如图

**Comment by lmk123** [comment]
看了一下确实有这个问题，有道翻译的官网上是正常的。

**Comment by yinzishao** [comment]
我也是有这个问题

**Comment by lmk123** [comment]
已发布 v6.4.4 版本修复有道和谷歌不能用的问题
