### ISSUE TITLE
Hi 我可以在本地增加自己的翻译接口吗？

### ISSUE THREAD

**Issue by Xinghanzzy** [Selection-Translator/crx-selection-translate#550]
我有实验室自己开发的内网使用的翻译接口 我可以通过一些方法自己把我的接口加进来然后本地使用吗？
平时常用python

**Comment by lmk123** [comment]
目前划词翻译没有这个功能（其实我之前是有想到过的，但这个功能感觉太小众了，后来就没加）

如果你会写一点 JavaScript，那你可以自己改代码：

1. 首先，git clone 下 https://github.com/Selection-Translator/crx-selection-translate 和 https://github.com/Selection-Translator/translation.js
2. 在 translation.js 里加上你自己的接口，只要你保证数据结构和 translation.js 的一致就可以了
3. 修改 crx-selection-translate [package.json](https://github.com/Selection-Translator/crx-selection-translate/blob/master/package.json)，将 dependencies 里的 translation.js 指向你本地的 translation.js，例如 "translation.js": "file:/path/to/translation.js" [package.json 相关文档](https://docs.npmjs.com/files/package.json#local-paths)
4. 在 crx-selection-translate 的代码中将默认的翻译接口从谷歌改为你自己加的那个，然后打包成一个扩展程序

这样你就可以把这个扩展程序安装到你自己的浏览器里使用了
