### ISSUE TITLE
可读取权限设置成“当你点击此扩展程序时”就报错“网络错误，请检查你的网络设置。”

### ISSUE THREAD

**Issue by lkkljk** [Selection-Translator/crx-selection-translate#552]
“可读取和更改网站数据”设置为“在所有网站上”时是正常的，但是设置成“当你点击此扩展程序时”就报错“网络错误，请检查你的网络设置。”
希望尽快修复一下，谢谢!

**Comment by lmk123** [comment]
这根本不算是一个问题，划词翻译需要注入到每个网站里面，这样网页划词翻译才能生效，所以需要“在所有网站上”

设置成“点击时”相当于没有给划词翻译任何网站的权限，连同查询翻译结果所需的网络权限也没了，所以就会出现“网络问题”。
