### ISSUE TITLE
接口返回了错误的数据，请稍候重试

### ISSUE THREAD

**Issue by TGich** [Selection-Translator/crx-selection-translate#559]
接口返回了错误的数据，请稍候重试。有道翻译会返回这个，建议增加入口可以设置为自己的有道应用ID和应用密钥，这样可以减少作者的使用限额

**Comment by javmain** [comment]
这里也提示相同的错误，建议可以提供可配置功能。

**Comment by KseeleK** [comment]
我这里突然也出现这个问题，每种翻译方式都报这个错

**Comment by boyliuxiaopeng** [comment]
接口返回了错误的数据，请稍候重试。 重试 via 有道翻译

**Comment by javmain** [comment]
https://github.com/crimx/ext-saladict  大家用这个吧，这个人项目应该黄了

**Comment by boyliuxiaopeng** [comment]
> https://github.com/crimx/ext-saladict 大家用这个吧，这个人项目应该黄了

不知道什么情况，感谢分享！

**Comment by lmk123** [comment]
已发布 v6.4.4 版本修复有道和谷歌不能用的问题
