### ISSUE TITLE
修改安装后的程序文件，导致插件损坏

### ISSUE THREAD

**Issue by asgg4321** [Selection-Translator/crx-selection-translate#567]
我想修改程序的背景颜色，通过修改popup.css中的第一个background-color和common1.css文件中的颜色设置，出现程序损坏，如果插件开始设置一键换皮肤的功能就更好了，谢谢你的贡献，使用这个插件读pdf论文非常方便

**Comment by lmk123** [comment]
新版本会调整一下界面和颜色的，这样你就不用自己去改了，敬请期待吧 😂

**Comment by asgg4321** [comment]
好的，谢谢

**Comment by asgg4321** [comment]
原因已经知道了，是谷歌浏览器为了防止恶意程序修改文件设置的安全机制
