### ISSUE TITLE
希望增加火狐插件

### ISSUE THREAD

**Issue by 1tonsilla** [Selection-Translator/crx-selection-translate#574]
希望能添加到火狐插件里，谢谢~！

**Comment by ZwinR** [comment]
前来助攻

**Comment by lxr0630** [comment]
因为火狐上没有这个插件，所以这是我不用火狐浏览器的原因之一。

**Comment by yousifun** [comment]
哈哈，我也很希望能有火狐插件。

**Comment by RemRemRemRe** [comment]
帮顶，这是我用过的最棒的划词翻译插件，能显示音标更好

**Comment by Edwardvi** [comment]
希望可以加入火狐

**Comment by RemRemRemRe** [comment]
> 
> 
> 帮顶，这是我用过的最棒的划词翻译插件，能显示音标更好

火狐上可以用 沙拉查词https://saladict.crimx.com/

**Comment by lmk123** [comment]
已上架火狐商店。 https://addons.mozilla.org/zh-CN/firefox/addon/hcfy/

如果在火狐里使用遇到问题，欢迎反馈。
