### ISSUE TITLE
谷歌国内和有道翻译都无法用，就一个百度可以用

### ISSUE THREAD

**Issue by ssguaishou** [Selection-Translator/crx-selection-translate#575]
很难受。。

**Comment by lmk123** [comment]
有道翻译已经修复了，谷歌我正在修，预计今天晚上会发个版本

**Comment by ldw4033** [comment]
为啥我的有道，不能输入id和密钥

**Comment by lmk123** [comment]
已发布 v6.4.4 版本修复有道和谷歌不能用的问题

**Comment by ssguaishou** [comment]
多谢大佬





------------------ 原始邮件 ------------------
发件人: "mingkaili"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 凌晨1:25
收件人: "Selection-Translator/crx-selection-translate"<crx-selection-translate@noreply.github.com>;
抄送: "刘浩东"<775971551@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Selection-Translator/crx-selection-translate] 谷歌国内和有道翻译都无法用，就一个百度可以用 (#575)




已发布 v6.4.4 版本修复有道和谷歌不能用的问题
