### ISSUE TITLE
Chrome 71 更新到划词翻译 v6.4.4 之后不能用了

### ISSUE THREAD

**Issue by tortoo** [Selection-Translator/crx-selection-translate#577]
作者更新：**将 Chrome 升级到 v72 及以上版本或者将划词翻译升级到 v6.4.5 即可**
-------------------------------
昨天还好好的，今天发现不灵了，才看到 15 小时前更新了。症状是一直显示下图：
![image](https://user-images.githubusercontent.com/28673736/56884652-09e62c00-6a9d-11e9-822f-79dfa9ba3a80.png)
然后快捷键也不灵了，就是选定网页上的一段然后翻译的快捷键，没动静。我是OS X 10.11.6系统，chrome 版本71.0.3578.98

**Comment by lmk123** [comment]
我也碰到这个问题了，但是刷新一下就好了，我正在看，预计今晚修复

**Comment by tortoo** [comment]
@lmk123 感谢哈！不过我这里刷新还是不行……

**Comment by lmk123** [comment]
我昨晚试了一下，我也没法 100% 重现这个问题，但在我重启了下浏览器后就没再出现这个问题了，你可以试试看重启能不能解决

**Comment by mars00772** [comment]
是否可以双击单词自动弹出翻译？

**Comment by hzhebin** [comment]
me too

**Comment by lyle8341** [comment]
连接到翻译引擎时发生了错误，请刷新网页或重启浏览器后再试.

**Comment by lyle8341** [comment]
连接到翻译引擎时发生了错误，请刷新网页或重启浏览器后再试,

> 浏览器重启,电脑重启都没有用

.                                         
当前版本：v6.4.4                   chrome:版本 71.0.3578.98（正式版本） （64 位）

**Comment by DIYer22** [comment]
一样的问题 突然就不行了, 我临时解决方案是卸载掉插件,  手动下载并重新装 V6.4 版的 `.crx`:

https://github.com/Selection-Translator/crx-selection-translate/releases/tag/v6.4.0

**Comment by oufu99** [comment]
更到6.4.4就不行了,然后按照楼上的方法装了6.4  但是重新开了一下chrome就又自动更新到6,4,4 快崩溃了...

**Comment by tortoo** [comment]
@lmk123 重启了浏览器，还是不灵，囧……感觉应该不是翻译源和网络的问题，换其他引擎都是一样症状，快捷键也不灵了，感觉可能是接口没对上。回滚到前一版的接口吧，源换不换应该问题不大，之前用了很久几乎没有问题

**Comment by oufu99** [comment]
刚才怎么弄都不行...后面我把chrome升了下级就可以了,原来是71.0  现在是74.0.3729.108  就好了

**Comment by nm46nm** [comment]
同样的问题……，重启浏览器也不管用

**Comment by yeahpeng** [comment]
遇到同样的问题, 重启浏览器 + 重装插件都不管用

**Comment by yeahpeng** [comment]
> 刚才怎么弄都不行...后面我把chrome升了下级就可以了,原来是71.0 现在是74.0.3729.108 就好了

升级chrome到最新版后正常

**Comment by tortoo** [comment]
@lmk123  chrome刚升级到了 74 版本，灵了！但是测了下，谷歌国内国外、百度都可以，有道还是不行，显示如下图：
![image](https://user-images.githubusercontent.com/28673736/56946526-dff43e80-6b5c-11e9-8d80-a0e478171cea.png)
虽然我不用有道，但可能其他人需要。
另外，可能有相当部分人不愿意升级 chrome，因为系统性能限制，所以要是6.4 版本能用而且重启 chrome不自动更新就好了，两个版本共存，旧版不再更新。建议作者还能测下 72、73 版本灵不灵，还是都要升到 74，然后公示下，大家好作选择

**Comment by lmk123** [comment]
已定位到问题，正在修复，预计半小时内发新版本

**Comment by yousifun** [comment]
我也遇到这样的问题，百分浏览器 chromiun70内核，卸载重装也没有用。更换chrome 74版本，功能正常。

![2019-04-30_21-57-58.png](https://i.loli.net/2019/04/30/5cc854e69d97c.png)

**Comment by lmk123** [comment]
已经发布 v6.4.5 版本，麻烦大家手动更新一下，并反馈一下这个问题修复了没有

**Comment by lmk123** [comment]
> @lmk123 chrome刚升级到了 74 版本，灵了！但是测了下，谷歌国内国外、百度都可以，有道还是不行，显示如下图：
> ![image](https://user-images.githubusercontent.com/28673736/56946526-dff43e80-6b5c-11e9-8d80-a0e478171cea.png)

我这边有道是正常的，我猜可能是因为有道翻译的接口不是 https 的所以被运营商劫持了，一般过会儿就会恢复。如果明天你还有这个问题，麻烦重新开个 issue，提供一下具体信息

**Comment by yousifun** [comment]
chromiun 70内核，最新版本插件功能正常。
