### ISSUE TITLE
更新到 6.4.5 版后有道翻译依然连不上

### ISSUE THREAD

**Issue by tortoo** [Selection-Translator/crx-selection-translate#580]
其他一切正常，有道还是显示接口错误：
![image](https://user-images.githubusercontent.com/28673736/57004435-90b41980-6c01-11e9-88f6-b3b6ab987c50.png)
我的系统是 OS X 10.11.6，chrome 版本为最新的 74 版本。运营商是天津中国移动光纤

**Comment by P-256** [comment]
系统bug10，chrome为74，运营商湖南电信，你的是被劫持了吗？我的6.4.4和6.4.5都没问题

**Comment by tortoo** [comment]
@P-256 昨天就试了 DNSCrypt，但是没用，会全都失灵，都提示接口错误。关闭 DNSCrypt后，其他又都能正常翻译，有道还是照旧，提示接口错误

**Comment by wmdsjhjcmd** [comment]
6.4.5 有道翻译，提示接口错误
![image](https://user-images.githubusercontent.com/16767658/63558720-a074b680-c580-11e9-8947-5c93fd73d4fd.png)

**Comment by lmk123** [comment]
已经发布了 v6.4.6 解决有道翻译的问题，更新一下试试
