### ISSUE TITLE
和chrome自带的翻译功能有冲突

### ISSUE THREAD

**Issue by yelw145** [Selection-Translator/crx-selection-translate#590]
![FireShot Capture 032 - 主页·选择 - 翻译_ crx-selection-translate Wiki·GitHub - github com](https://user-images.githubusercontent.com/48408124/59482224-9193c880-8e9a-11e9-989e-33b8af3b7961.png)
![FireShot Capture 031 - Home · Selection-Translator_crx-selection-translate Wiki · GitHub_ - github com](https://user-images.githubusercontent.com/48408124/59482230-99536d00-8e9a-11e9-82df-033056e5d2d5.png)

**Comment by lmk123** [comment]
这个冲突是不可避免的，Chrome 自带的翻译功能会把网页整个翻译一遍，而划词翻译的弹窗也是网页的一部分。
