### ISSUE TITLE
有道接口返回错误

### ISSUE THREAD

**Issue by Blueria** [Selection-Translator/crx-selection-translate#594]
![微信截图_20190711095933](https://user-images.githubusercontent.com/7038130/61016631-dee45680-a3c2-11e9-8130-1a406bc3cb5b.png)

插件版本：6.4.5

**Comment by hackgyj** [comment]
有道的好像一直用不了

**Comment by yellowgg** [comment]
能用，最近才出现错误的。 是不是作者的接口过期了啥的

**Comment by a13700938514** [comment]
嗯嗯，是的，我之前也是选的有道的翻译引擎，但是最近就出现接口错误了，移除重新下载后也是。而且有道的很多翻译，比谷歌中国和谷歌翻译的准确率高很多。希望作者检查下有道的接口，万分感谢

**Comment by DarkSherlock** [comment]
有道的翻译确实比较好，希望作者看看是不是接口过期了，还是有道升级了接口要做下调整

**Comment by bowencool** [comment]
![image](https://user-images.githubusercontent.com/20217146/61759477-26270a00-adfb-11e9-8258-38b1e5bd22d7.png)

**Comment by ElfSundae** [comment]
Same here

**Comment by baiyuting** [comment]
+1

**Comment by whatqiu** [comment]
+1

**Comment by lmk123** [comment]
已更新 v6.4.6 解决有道翻译的问题，大家更新一下试试
