### ISSUE TITLE
火狐插件能实现吗？

### ISSUE THREAD

**Issue by Ldada** [Selection-Translator/crx-selection-translate#595]
火狐插件能实现吗？

**Comment by Ldada** [comment]
### Are firefox and chrome plugins not compatible?Can someone extend the plugin for firefox?
### **firefox**和**chrome**的插件不是可以兼容吗？有人能为firefox扩展插件吗？

**Comment by Ldada** [comment]
**兼容性检测**  **Firefox官方检测网站**：https://www.extensiontest.com/

**测试结果**：
       

> Extension Compatibility Test for Firefox
Firefox扩展兼容性测试
> 
> Great news! Your extension is compatible with Firefox.
好消息！您的扩展程序与Firefox兼容。


![image](https://user-images.githubusercontent.com/42060663/61042241-6901de80-a406-11e9-9b5a-d50271d1e951.png)



完整测试报告 [report.txt](https://github.com/Selection-Translator/crx-selection-translate/files/3381472/report.txt)

**Comment by Ldada** [comment]
### 测试发现部分文件头部存在部分错误_

> {
	src / background - scripts / badge.js ", /
	src / background - scripts / commands.js ", /
	src / background - scripts / index.js ", /
	src / background - scripts / install.js ", /
	src / background - scripts / menus.js ", /
	src / background - scripts / pdf - sniffer.js ", /
	src / background - scripts / server.js ", /
	src / content - scripts / client.js ", /
	src / content - scripts / index.js ", /
	src / content - scripts / server.js ", /
	src / content - scripts / st / draggable.js ", /
	src / content - scripts / st / ga.js ", /
	src / content - scripts / st / hide - on - esc.js ", /
	src / content - scripts / st / index.js ", /
	src / content - scripts / st / restrict.js ", /
	src / content - scripts / st / shanbay.js ", /
	src / content - scripts / st / storage.js ", /
	src / options / about / index.js ", /
	src / options / index.js ", /
	src / options / settings / index.js ", /
	src / popup / app.js ", /
	src / popup / client.js ", /
	src / popup / index.js ", /
	src / popup / st.js ",/
	src / public / clipboard.js ", /
	src / public /default -options.js ", /
	src / public / ga.js ", /
	src / public / locales.js ", /
	src / public / my - ts.js ", /
	src / public / storage - watcher.js ", /
	src / public / util.js ", /
	src / public / widget / index.js ", /
	src / public / widget / vue - st.js ", /
}

### 完整测试报告json文件如下：
{"compat":[],"errors":[{"message":"JavaScript syntax error","description":"There is a JavaScript syntax error in your code; validation cannot continue on this file.","locations":[{"file":"crx-selection-translate-6.4.4/src/background-scripts/badge.js","line":5},{"file":"crx-selection-translate-6.4.4/src/background-scripts/commands.js","line":5},{"file":"crx-selection-translate-6.4.4/src/background-scripts/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/background-scripts/install.js","line":4},{"file":"crx-selection-translate-6.4.4/src/background-scripts/menus.js","line":5},{"file":"crx-selection-translate-6.4.4/src/background-scripts/pdf-sniffer.js","line":5},{"file":"crx-selection-translate-6.4.4/src/background-scripts/server.js","line":4},{"file":"crx-selection-translate-6.4.4/src/content-scripts/client.js","line":1},{"file":"crx-selection-translate-6.4.4/src/content-scripts/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/content-scripts/server.js","line":5},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/draggable.js","line":5},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/ga.js","line":5},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/hide-on-esc.js","line":5},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/restrict.js","line":5},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/shanbay.js","line":1},{"file":"crx-selection-translate-6.4.4/src/content-scripts/st/storage.js","line":5},{"file":"crx-selection-translate-6.4.4/src/options/about/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/options/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/options/settings/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/popup/app.js","line":5},{"file":"crx-selection-translate-6.4.4/src/popup/client.js","line":1},{"file":"crx-selection-translate-6.4.4/src/popup/index.js","line":1},{"file":"crx-selection-translate-6.4.4/src/popup/st.js","line":5},{"file":"crx-selection-translate-6.4.4/src/public/clipboard.js","line":5},{"file":"crx-selection-translate-6.4.4/src/public/default-options.js","line":8},{"file":"crx-selection-translate-6.4.4/src/public/ga.js","line":29},{"file":"crx-selection-translate-6.4.4/src/public/locales.js","line":4},{"file":"crx-selection-translate-6.4.4/src/public/my-ts.js","line":4},{"file":"crx-selection-translate-6.4.4/src/public/storage-watcher.js","line":5},{"file":"crx-selection-translate-6.4.4/src/public/util.js","line":5},{"file":"crx-selection-translate-6.4.4/src/public/widget/index.js","line":5},{"file":"crx-selection-translate-6.4.4/src/public/widget/vue-st.js","line":27},{"file":"crx-selection-translate-6.4.4/tests/src/background-scripts/badge-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/background-scripts/commands-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/background-scripts/install-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/background-scripts/menus-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/background-scripts/server-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/index-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/server-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/st/draggable-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/st/hide-on-esc-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/st/restrict-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/content-scripts/st/storage-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/options/about/index-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/options/settings/index-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/popup/app-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/popup/st-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/public/clipboard-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/public/storage-watcher-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/public/util-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/public/widget/index-spec.js","line":1},{"file":"crx-selection-translate-6.4.4/tests/src/public/widget/vue-st-spec.js","line":1}]}],"warnings":[]}

**Comment by lmk123** [comment]
已上架火狐商店。 https://addons.mozilla.org/en-US/firefox/addon/hcfy/

**Comment by Ldada** [comment]
@lmk123  火狐插件版本很好用，目前使用新版火狐浏览器，翻译速度很快，比chrome内体验好很多，是又重构了firefox版本吗，，非常感谢作者持续更新🌻！
