### ISSUE TITLE
能否为 pdf.js 添加标注功能

### ISSUE THREAD

**Issue by cocobrime** [Selection-Translator/crx-selection-translate#599]
插件带的```pdf.js```没有标注功能，我看到有人已经为```pdf.js```添加过这个功能，能否整合进```划词翻译```中？

这个是相关链接：[实现pdf.js添加批注（注解）功能/书签保存/高亮文本/测量功能/自由手绘/箭头/下划线](https://blog.csdn.net/xxx6450/article/details/82930318)

**Comment by lmk123** [comment]
给 PDF 添加标注功能不是划词翻译应该做的，加入 pdf 翻译功能也是为了方便用户翻译，而不是为了成为另一个 pdf 阅读器，所以我不打算整合标注功能。
