### ISSUE TITLE
双击翻译在 Linux Chrome 47 中失效

### ISSUE THREAD

**Issue by jiajunhuang** [Selection-Translator/crx-selection-translate#60]
我认为应该尽量减少用户从点击到得到翻译结果的成本？
尽管目前的做法可能是考虑到用户不希望每次双击都弹出翻译。
不过希望可以考虑增加一个选项，双击直接翻译。

**Comment by lmk123** [comment]
已有功能 :)

**Comment by jiajunhuang** [comment]
应该是Linux/Chrome 47失效

**Comment by lmk123** [comment]
目前我只在 Mac OS 和 Windows 上测试过，为了重现你的问题我需要安装一个 Linux 虚拟机，这可能会花一点时间。
