### ISSUE TITLE
有道翻译提示错误

### ISSUE THREAD

**Issue by ArvinChen9539** [Selection-Translator/crx-selection-translate#600]
![image](https://user-images.githubusercontent.com/20532645/62989531-fc518800-be7a-11e9-83bf-3c634b6e2792.png)

**Comment by cxhttt233** [comment]
同

**Comment by Z4Knight** [comment]
me too

**Comment by kbill4345** [comment]
一样

**Comment by lmk123** [comment]
已发布 v6.4.6 解决有道翻译的问题，大家更新一下试试
