### ISSUE TITLE
github上下载的文件解压之后，提示项目清单缺失

### ISSUE THREAD

**Issue by CasualMing** [Selection-Translator/crx-selection-translate#605]
由于某种原因，无法使用谷歌应用商店安装插件，然后去github上下载的文件解压之后，提示项目清单缺失

**Comment by lmk123** [comment]
你是下载了源代码吗？出现这种情况一般是因为网络不稳定导致的。

如果你是想安装划词翻译，只需要到 https://github.com/Selection-Translator/crx-selection-translate/releases/latest 下载 .crx 文件并拖放到 chrome://extensions/ 就可以了
