### ISSUE TITLE
Firefox 上无法保存设置

### ISSUE THREAD

**Issue by wuhgit** [Selection-Translator/crx-selection-translate#609]
@lmk123

扩展版本：v6.4.8.1
Firefox 版本：69.0.3 (64 位)

问题描述：

在扩展选项中修改设置，切换任意标签（包括此设置中的标签，比如先修改设置，然后点击关于，再回到设置）后设置恢复默认。

卸载重装扩展、卸载重装Firefox 均如此。

![201910161309](https://user-images.githubusercontent.com/24295575/66889806-56ef9780-f016-11e9-88d5-436a86efb050.gif)

**Comment by lmk123** [comment]
感谢反馈！我已经发布了 v6.4.8.2 修复了这个问题，你可以试一下，如果还是有问题，欢迎留言。

**Comment by wuhgit** [comment]
@lmk123

更新后功能正常了，非常感谢！！！
