### ISSUE TITLE
功能已经够用了。。我就想知道快捷键那个设置在哪里TAT

### ISSUE THREAD

**Issue by rhua0012** [Selection-Translator/crx-selection-translate#613]
设置里说想要先选中再翻译的话要去“更多工具” -> “扩展程序” -> 最右下角的“键盘快捷键”那里设置。。找不到这个“更多工具“在哪里。。有哪个朋友知道吗

**Comment by rhua0012** [comment]
*先选中再翻译 
打错了TAT

**Comment by lmk123** [comment]
如图

![image](https://user-images.githubusercontent.com/5035625/67372340-53c55000-f5b0-11e9-8593-3cfc7f117e2d.png)
