### ISSUE TITLE
所有翻译引擎都失败！

### ISSUE THREAD

**Issue by jsonleex** [Selection-Translator/crx-selection-translate#620]
![Screenshot from 2019-11-04 16-01-40](https://user-images.githubusercontent.com/25883665/68106637-392e9780-ff1d-11e9-8799-0373a61618f3.png)

**Comment by lmk123** [comment]
我这里都是正常的，重启一下浏览器试试？

**Comment by jsonleex** [comment]
我本地环境配置信息

- 系统：Linux 5.3.0-19-generic #20-Ubuntu x86_64 GNU/Linux
- 浏览器：Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)
- 插件版本：划词翻译@6.4.8

从 background page 报错日志来看，错误是“跨域”导致的。

**Comment by lmk123** [comment]
划词翻译申请过这些域名的访问权限，正常来讲是可以跨域访问的，你重启过浏览器也没用？

**Comment by jsonleex** [comment]
是的，我刚更新了系统，顺便把浏览器也更新了，依然是这样。

**Comment by lmk123** [comment]
确认一下扩展详细信息页的「有权访问的网站」是不是选择的「在所有网站上」？

chrome://extensions/?id=ikhdkkncnoglghljlkmcimlnlhkeamad

如果确实是选择的在所有网站上，那重装一下划词翻译试试吧 😂 

![image](https://user-images.githubusercontent.com/5035625/68177941-f0321e00-ffc4-11e9-892d-20f4b18f309b.png)

**Comment by jsonleex** [comment]
非常感谢，我之前选择的是“点击时”，现在改为“在所有网站上”可以翻译成功。但是我并不希望在浏览所有网页的时候都加载这个插件，希望能做到“需要时唤出”就好了，另外：非常感谢你提供的这款插件♥️。

**Comment by jsonleex** [comment]
> 非常感谢，我之前选择的是“点击时”，现在改为“在所有网站上”可以翻译成功。但是我并不希望在浏览所有网页的时候都加载这个插件，希望能做到“需要时唤出”就好了，另外：非常感谢你提供的这款插件。

更正一下，是我的使用方式不对，修改插件配置，可以实现“需要时唤出”的效果。

再次感谢作者大大。
