### ISSUE TITLE
有道翻译无法使用

### ISSUE THREAD

**Issue by palemoky** [Selection-Translator/crx-selection-translate#629]
![](https://tva1.sinaimg.cn/large/006tNbRwly1g9kilruketj308v04tglu.jpg)

划词翻译版本：v6.4.8
macOS 版本：10.15.1
Chrome 版本：78.0.3904.108

个人感觉有的结果很好用，但大概半年前有道就失效了，请问如何修复该问题？

**Comment by lmk123** [comment]
我试了下有道翻译是正常的，你是在什么情况下失效了，能给出一个重现的步骤吗

**Comment by palemoky** [comment]
> 我试了下有道翻译是正常的，你是在什么情况下失效了，能给出一个重现的步骤吗

我刚重试了一下，竟然奇迹般的好了。这个问题复现的话，就是之前我选择了有道，然后点击翻译就会出现。
