### ISSUE TITLE
我参考你的插件写了一个 Mac 端软件

### ISSUE THREAD

**Issue by ripperhe** [Selection-Translator/crx-selection-translate#635]
你的插件很好用，不过不在浏览器的时候没法使用，所以我参考你的软件写了一个 Mac 端 APP
你的插件给我提供了很多现成的 API ，特此感谢
https://github.com/ripperhe/Bob

**Comment by lmk123** [comment]
不用谢，我开源的目的之一就是帮助其它项目减少开发成本，很高兴能帮助到你。
