### ISSUE TITLE
新版 edge 浏览器已使用 Chromium 内核，能否上架 win 10 商店

### ISSUE THREAD

**Issue by wkjcn** [Selection-Translator/crx-selection-translate#642]

**Comment by xiaotan0305** [comment]
@wkjcn @wenzhixin @lmk123 @xiekeyi98 @lxfly2000 
商店地址：
https://microsoftedge.microsoft.com/addons/category/Edge-Extensions?hl=zh-CN

**Comment by lmk123** [comment]
划词翻译已上架 Edge 商店 https://microsoftedge.microsoft.com/addons/detail/oikmahiipjniocckomdccmplodldodja
