### ISSUE TITLE
请求朗读"原文".目前朗读功能只能朗读翻译后的文字.

### ISSUE THREAD

**Issue by itwarlock** [Selection-Translator/crx-selection-translate#652]
一般来说.翻译后的"中文",大家都会读会认,不太需要朗读发声.
谢谢

**Comment by lmk123** [comment]
原文朗读功能是有的，只是藏的比较深。。你要点右上角的三角箭头展开，然后会出现“翻译”按钮，把鼠标放在翻译按钮上，就会出现“朗读”按钮了
