### ISSUE TITLE
请问谷歌国内翻译域名是什么？我要设置代理

### ISSUE THREAD

**Issue by htqx** [Selection-Translator/crx-selection-translate#653]
我发现一个问题，就是代理用pac模式，用默认的国内翻译也是会出现问题的，究竟是什么原理？

你的工具调用的api是什么 域名，我看看能否把它添加到直通里面。

谢谢。

希望能够增加一个在使用代理的时候也能使用的模式，毕竟优先国内翻译，速度会好一些。

还有，第一次发现你们也是有github的，这个工具我很喜欢，感谢你们的劳动！

**Comment by lmk123** [comment]
国内的谷歌翻译接口是 https://translate.google.cn
国际版谷歌翻译接口是 https://translate.google.com

很高兴你喜欢我们的工具
